---
sidebar: sidebar 
permalink: trident-docker/deploy-docker.html 
keywords: deploy, Trident, trident for docker, docker 
summary: Trident for Dockerは、NetAppストレージプラットフォームのDockerエコシステムと直接統合できます。ストレージプラットフォームから Docker ホストまで、ストレージリソースのプロビジョニングと管理をサポートします。また、将来プラットフォームを追加するためのフレームワークもサポートします。 
---
= Tridentの導入
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident for Dockerは、NetAppストレージプラットフォームのDockerエコシステムと直接統合できます。ストレージプラットフォームから Docker ホストまで、ストレージリソースのプロビジョニングと管理をサポートします。また、将来プラットフォームを追加するためのフレームワークもサポートします。

同じホスト上でTridentの複数のインスタンスを同時に実行できます。これにより、複数のストレージシステムとストレージタイプへの同時接続が可能になり、 Docker ボリュームに使用するストレージをカスタマイズできます。

.必要なもの
を参照してくださいlink:prereqs-docker.html["導入の前提条件"]。前提条件を満たしていることを確認したら、Tridentを導入する準備が整います。



== Docker Managed Plugin メソッド（バージョン 1.13 / 17.03 以降）

.作業を開始する前に

NOTE: 従来のデーモンメソッドでDocker 1.13/17.03より前のTridentを使用している場合は、マネージプラグインメソッドを使用する前に、Tridentプロセスを停止してDockerデーモンを再起動してください。

. 実行中のインスタンスをすべて停止します。
+
[source, console]
----
pkill /usr/local/bin/netappdvp
pkill /usr/local/bin/trident
----
. Docker を再起動します。
+
[source, console]
----
systemctl restart docker
----
. Docker Engine 17.03 （新しい 1.13 ）以降がインストールされていることを確認します。
+
[source, console]
----
docker --version
----
+
バージョンが最新でない場合は、 https://docs.docker.com/engine/install/["インストール環境をインストールまたは更新します"^]。



.手順
. 構成ファイルを作成し、次のオプションを指定します。
+
** `config`: デフォルトのファイル名は 'config.json ですが ' ファイル名に config オプションを指定することで ' 選択した任意の名前を使用できます構成ファイルは ' ホスト・システムの /etc/netappdvp ディレクトリに格納されている必要があります
** 「 log-level 」：ログレベルを指定します（「 debug` 」、「 info 」、「 warn 」、「 error 」、「 fatal 」）。デフォルトは「 info 」です。
** `ebug`: デバッグログを有効にするかどうかを指定します。デフォルトは false です。true の場合、ログレベルを上書きします。
+
... 構成ファイルの場所を作成します。
+
[source, console]
----
sudo mkdir -p /etc/netappdvp
----
... 構成ファイルを作成します
+
[source, console]
----
cat << EOF > /etc/netappdvp/config.json
----
+
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
EOF
----




. 管理プラグインシステムを使用してTridentを起動します。を、使用しているプラグインのバージョン（xxx.xx.x）に置き換えます `<version>`。
+
[source, console]
----
docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:<version> config=myConfigFile.json
----
. Tridentを使用して、構成済みシステムのストレージを消費します。
+
.. 「 firstVolume 」という名前のボリュームを作成します。
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
.. コンテナの開始時にデフォルトのボリュームを作成します。
+
[source, console]
----
docker run --rm -it --volume-driver netapp --volume secondVolume:/my_vol alpine ash
----
.. ボリューム「 firstVolume 」を削除します。
+
[source, console]
----
docker volume rm firstVolume
----






== 従来の方法（バージョン 1.12 以前）

.作業を開始する前に
. バージョン 1.10 以降の Docker がインストールされていることを確認します。
+
[source, console]
----
docker --version
----
+
使用しているバージョンが最新でない場合は、インストールを更新します。

+
[source, console]
----
curl -fsSL https://get.docker.com/ | sh
----
+
または https://docs.docker.com/engine/install/["ご使用のディストリビューションの指示に従ってください"^]。

. NFS または iSCSI がシステムに対して設定されていることを確認します。


.手順
. NetApp Docker Volume Plugin をインストールして設定します。
+
.. アプリケーションをダウンロードして開梱します。
+
[source, console]
----
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar zxf trident-installer-25.06.0.tar.gz
----
.. ビンパス内の場所に移動します。
+
[source, console]
----
sudo mv trident-installer/extras/bin/trident /usr/local/bin/
sudo chown root:root /usr/local/bin/trident
sudo chmod 755 /usr/local/bin/trident
----
.. 構成ファイルの場所を作成します。
+
[source, console]
----
sudo mkdir -p /etc/netappdvp
----
.. 構成ファイルを作成します
+
[source, console]
----
cat << EOF > /etc/netappdvp/ontap-nas.json
----
+
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
EOF
----


. バイナリを配置して構成ファイルを作成したら、目的の構成ファイルを使用してTridentデーモンを起動します。
+
[source, console]
----
sudo trident --config=/etc/netappdvp/ontap-nas.json
----
+

NOTE: 指定されていない場合、ボリュームドライバのデフォルト名は「NetApp」です。

+
デーモンを起動したら、Docker CLIインターフェイスを使用してボリュームを作成および管理できます。

. ボリュームを作成します
+
[source, console]
----
docker volume create -d netapp --name trident_1
----
. コンテナの開始時に Docker ボリュームをプロビジョニング：
+
[source, console]
----
docker run --rm -it --volume-driver netapp --volume trident_2:/my_vol alpine ash
----
. Docker ボリュームを削除します。
+
[source, console]
----
docker volume rm trident_1
----
+
[source, console]
----
docker volume rm trident_2
----




== システム起動時にTridentを起動する

システムベースのシステムのサンプルユニットファイルは、から入手できます `contrib/trident.service.example` Gitリポジトリで実行します。RHELでファイルを使用するには、次の手順を実行します。

. ファイルを正しい場所にコピーします。
+
複数のインスタンスを実行している場合は、ユニットファイルに一意の名前を使用してください。

+
[source, console]
----
cp contrib/trident.service.example /usr/lib/systemd/system/trident.service
----
. ファイルを編集し、概要（ 2 行目）を変更してドライバ名と構成ファイルのパス（ 9 行目）を環境に合わせます。
. 変更を取り込むためにシステムをリロードします。
+
[source, console]
----
systemctl daemon-reload
----
. サービスを有効にします。
+
この名前は '/usr/lib/systemd/system' ディレクトリ内のファイルの名前によって異なります

+
[source, console]
----
systemctl enable trident
----
. サービスを開始します。
+
[source, console]
----
systemctl start trident
----
. ステータスを確認します。
+
[source, console]
----
systemctl status trident
----



NOTE: ユニット・ファイルを変更するときは ' 変更を認識するために 'systemctl daemon-reload コマンドを実行します
