---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, fc, nvme 
summary: Tridentを導入する前に、必要なプロトコルの前提条件をホストにインストールして設定する必要があります。 
---
= 導入の前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentを導入する前に、必要なプロトコルの前提条件をホストにインストールして設定する必要があります。



== 要件を確認します

* の導入がすべてを満たしていることを確認します link:../trident-get-started/requirements.html["要件"]。
* サポートされているバージョンの Docker がインストールされていることを確認します。Docker のバージョンが最新でない場合は、 https://docs.docker.com/engine/install/["インストールまたは更新します"^]。
+
[source, console]
----
docker --version
----
* プロトコルの前提条件がホストにインストールおよび設定されていることを確認します。




=== NFSツール

オペレーティングシステム用のコマンドを使用して、NFSツールをインストールします。

[role="tabbed-block"]
====
.RHEL 8以降
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: NFSツールをインストールしたあとにワーカーノードをリブートして、コンテナにボリュームを接続する際の障害を回避します。



=== iSCSIツール

使用しているオペレーティングシステム用のコマンドを使用して、iSCSIツールをインストールします。

[role="tabbed-block"]
====
.RHEL 8以降
--
. 次のシステムパッケージをインストールします。
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. iscsi-initiator-utils のバージョンが 6.2.0.874-2.el7 以降であることを確認します。
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. スキャンを手動に設定：
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. マルチパスを有効化：
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. 「 iscsid 」と「 multipathd 」が実行されていることを確認します。
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. 'iSCSI' を有効にして開始します
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. 次のシステムパッケージをインストールします。
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. open-iscsi バージョンが 2.0.874-5ubuntu2.10 以降（ bionic の場合）または 2.0.874-7.1ubuntu6.1 以降（ Focal の場合）であることを確認します。
+
[source, console]
----
dpkg -l open-iscsi
----
. スキャンを手動に設定：
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. マルチパスを有効化：
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. 「 open-iSCSI」 および「マルチパスツール」が有効で実行されていることを確認します。
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== NVMeツール

オペレーティングシステムに対応したコマンドを使用してNVMeツールをインストールします。

[NOTE]
====
* NVMeにはRHEL 9以降が必要です。
* Kubernetesノードのカーネルバージョンが古すぎる場合や、使用しているカーネルバージョンに対応するNVMeパッケージがない場合は、ノードのカーネルバージョンをNVMeパッケージで更新しなければならないことがあります。


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== FCツール

オペレーティングシステム用のコマンドを使用して、FCツールをインストールします。

* FC PVSでRHEL / Red Hat Enterprise Linux CoreOS（RHCOS）を実行するワーカーノードを使用する場合は、StorageClassでmountOptionを指定してインラインのスペース再生を実行します `discard`。を参照してください https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red Hat のドキュメント"^]。


[role="tabbed-block"]
====
.RHEL 8以降
--
. 次のシステムパッケージをインストールします。
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. マルチパスを有効化：
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. が実行中であることを確認し `multipathd`ます。
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. 次のシステムパッケージをインストールします。
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. マルチパスを有効化：
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. が有効で実行中であることを確認し `multipath-tools`ます。
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====