---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Trident構成で使用可能な設定オプションを参照してください。 
---
= ストレージ構成オプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident構成で使用可能な設定オプションを参照してください。



== グローバル構成オプション

これらの設定オプションは、使用するストレージプラットフォームに関係なく、すべてのTrident構成に適用されます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「バージョン」  a| 
構成ファイルのバージョン番号
 a| 
`1`



| 'torageDriverName'  a| 
ストレージドライバの名前
 a| 
`ontap-nas`、 `ontap-san`、 `ontap-nas-economy`、
`ontap-nas-flexgroup`、 `solidfire-san`



| 'toragePrefix'  a| 
ボリューム名のオプションのプレフィックス。デフォルト： `netappdvp_`。
 a| 
`staging_`



| 「 limitVolumeSize 」と入力します  a| 
ボリュームサイズに関するオプションの制限。デフォルト：""（強制なし）
 a| 
`10g`

|===

TIP: Elementバックエンドには（デフォルトを含めて）使用しない `storagePrefix`でください。デフォルトでは、 `solidfire-san`ドライバはこの設定を無視し、プレフィックスは使用しません。NetAppでは、Dockerボリュームマッピングに特定のtenantIDを使用するか、名前のマンジングが使用されている可能性がある場合には、DockerからDockerのバージョン、ドライバ情報、およびraw名が入力された属性データを使用することを推奨しています。

作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。「 size 」オプションは、すべてのコントローラタイプで使用できます。デフォルトのボリュームサイズの設定方法の例については、 ONTAP の設定に関するセクションを参照してください。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「 size 」  a| 
新しいボリュームのオプションのデフォルトサイズ。デフォルト： `1G`
 a| 
`10G`

|===


== ONTAP の設定

ONTAP を使用する場合は、上記のグローバル構成値に加えて、次のトップレベルオプションを使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「管理 LIF 」  a| 
ONTAP 管理 LIF の IP アドレス。Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を指定できます。
 a| 
`10.0.0.1`



| 「重複排除  a| 
プロトコル LIF の IP アドレス。

* ONTAP NASドライバ*：NetAppでは、を指定することを推奨しています `dataLIF`。指定しない場合、TridentはSVMからデータLIFをフェッチします。NFSのマウント処理に使用するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を指定すると、ラウンドロビンDNSを作成して複数のデータLIF間で負荷を分散できます。

* ONTAP SANドライバ*：iSCSIまたはFCには指定しないでください。Tridentは、を使用してlink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP の選択的LUNマップ"^]、マルチパスセッションの確立に必要なiSCSI LIFまたはFC LIFを検出します。が明示的に定義されている場合は、警告が生成され `dataLIF`ます。
 a| 
`10.0.0.2`



| 'VM'  a| 
使用する Storage Virtual Machine （管理 LIF がクラスタ LIF である場合は必須）
 a| 
`svm_nfs`



| 「ユーザ名」  a| 
ストレージデバイスに接続するユーザ名
 a| 
`vsadmin`



| 「 password 」と入力します  a| 
ストレージ・デバイスに接続するためのパスワード
 a| 
`secret`



| 「集約」  a| 
プロビジョニング用のアグリゲート（オプション。設定する場合は SVM に割り当てる必要があります）。ドライバの場合 `ontap-nas-flexgroup`、このオプションは無視されます。SVMに割り当てられたすべてのアグリゲートを使用して、FlexGroupボリュームがプロビジョニングされます。
 a| 
`aggr1`



| 「 AggreglimitateUsage 」と入力します  a| 
オプション。使用率がこの割合を超えている場合は、プロビジョニングを失敗させます
 a| 
`75%`



| 「 nfsvMountOptions 」のように入力します  a| 
NFS マウントオプションのきめ細かな制御。デフォルトは「 -o nfsvers=3 」です。* 「 ONTAP-NAS' 」および「 ONTAP-NAS-エコノミー 」ドライバ専用です。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["ここでは、 NFS ホストの設定情報を参照してください"^]。
 a| 
`-o nfsvers=4`



| 「 igroupName 」と入力します  a| 
Tridentでは、ノードごとにASを `netappdvp`作成および管理し `igroups`ます。

この値は変更したり省略したりすることはできません。

*でのみ使用できます `ontap-san` ドライバ*。
 a| 
`netappdvp`



| 「 limitVolumeSize 」と入力します  a| 
要求可能な最大ボリュームサイズ。
 a| 
`300g`



| qtreesPerFlexvol`  a| 
FlexVol あたりの最大 qtree 数は [50 、 300] の範囲で指定する必要があります。デフォルトは 200 です。

*のため `ontap-nas-economy` ドライバ。このオプションを使用すると、FlexVol あたりの最大qtree数をカスタマイズできます。
 a| 
`300`



 a| 
`sanType`
| *ドライバでのみサポートされてい `ontap-san`ます。*iSCSI、 `nvme`NVMe/TCP、または `fcp`SCSI over Fibre Channel（FC；SCSI over Fibre Channel）に対してを選択します `iscsi`。 | `iscsi` 空白の場合 


| `limitVolumePoolSize` | * `ontap-san-economy`および `ontap-san-economy`ドライバでのみサポートされています。*ONTAP ONTAP NASエコノミードライバおよびONTAP SANエコノミードライバでFlexVolサイズを制限します。  a| 
`300g`

|===
作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。

[cols="1,3,2"]
|===
| オプション | 説明 | 例 


| 「平和のための準備」を参照してください  a| 
スペースリザベーションモード `none` （シンプロビジョニング）または `volume` （シック）
 a| 
「 NONE 」



| 「ナプショットポリシー」  a| 
使用するSnapshotポリシー。デフォルトはです `none`
 a| 
「 NONE 」



| 「スナップショット予約」  a| 
Snapshotリザーブの割合。デフォルトはONTAP のデフォルトをそのまま使用する場合はです
 a| 
`10`



| 'plitOnClone  a| 
作成時に親からクローンをスプリットします。デフォルトはです `false`
 a| 
「偽」



| 「暗号化」  a| 
新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトは「false」です。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

バックエンドでNAEが有効になっている場合、TridentでプロビジョニングされたすべてのボリュームでNAEが有効になります。

詳細については、を参照してくださいlink:../trident-reco/security-reco.html["TridentとNVEおよびNAEとの連携"]。
 a| 
正しいです



| 「 unixPermissions 」  a| 
プロビジョニングされたNFSボリュームのNASオプション。デフォルトはです `777`
 a| 
`777`



| 「スナップショット方向」  a| 
ディレクトリにアクセスするためのNASオプション `.snapshot`。
 a| 
NFSv4の場合は「true」NFSv3の場合は「false」



| 「 exportPolicy 」と入力します  a| 
NFSエクスポートポリシーで使用するNASオプション。デフォルトはです `default`
 a| 
`default`



| 'ecurityStyle'  a| 
プロビジョニングされたNFSボリュームにアクセスするためのNASオプション。

NFSのサポート `mixed` および `unix` セキュリティ形式デフォルトはです `unix`。
 a| 
`unix`



| 「 filesystemtype 」です  a| 
ファイルシステムタイプを選択するためのSANオプション。デフォルトはです `ext4`
 a| 
`xfs`



| 階層ポリシー  a| 
使用する階層化ポリシー。デフォルトはです `none`。
 a| 
「 NONE 」

|===


=== スケーリングオプション

ドライバと `ontap-san`ドライバを使用すると、 `ontap-nas`DockerボリュームごとにONTAP FlexVolが作成されます。ONTAPは、クラスタノードあたり最大1000個のFlexVol、最大12、000個のFlexVolをサポートします。Dockerボリュームの要件がこの制限の範囲内に収まる場合、 `ontap-nas`Dockerボリューム単位のSnapshotやクローニングなど、FlexVolによって提供される追加機能のため、ドライバが推奨されるNASソリューションです。

FlexVol の制限で対応できる容量よりも多くの Docker ボリュームが必要な場合は、「 ONTAP - NAS - エコノミー」または「 ONTAP - SAN - エコノミー」ドライバを選択します。

 `ontap-nas-economy`ドライバは、自動的に管理されるFlexVolボリュームのプール内にONTAP qtreeを作成するため、一部の機能を犠牲にして、クラスタノードあたり100,000、クラスタあたり2,400,000というはるかに優れた拡張性を提供します。この `ontap-nas-economy`ドライバは、Dockerボリューム単位のSnapshotやクローニングをサポートしていません。


NOTE: Swarm は複数のノード間でのボリューム作成のオーケストレーションを行わないため 'ONTAP-NAS-エコノミー のドライバは現在 Docker Swarm ではサポートされていません

この `ontap-san-economy`ドライバは、自動的に管理されるFlexVolボリュームの共有プール内にONTAP LUNとしてDockerボリュームを作成します。この方法では、各FlexVolが1つのLUNに制限されることはなく、SANワークロードの拡張性も向上します。ストレージアレイに応じて、 ONTAP はクラスタあたり最大 16384 個の LUN をサポートします。このドライバは、ボリュームが下位の LUN であるため、 Docker ボリューム単位の Snapshot とクローニングをサポートします。

ドライバを選択する `ontap-nas-flexgroup`と、数十億個のファイルを含むペタバイト規模まで拡張可能な単一ボリュームへの並列処理を強化できます。FlexGroup のユースケースとしては、 AI / ML / DL 、ビッグデータと分析、ソフトウェアのビルド、ストリーミング、ファイルリポジトリなどが考えられます。Tridentでは、FlexGroupボリュームのプロビジョニング時に、SVMに割り当てられているすべてのアグリゲートが使用されます。Trident での FlexGroup のサポートでは、次の点も考慮する必要があります。

* ONTAP バージョン 9.2 以降が必要です。
* 本ドキュメントの執筆時点では、 FlexGroup は NFS v3 のみをサポートしています。
* SVM で 64 ビットの NFSv3 ID を有効にすることを推奨します。
* 推奨されるFlexGroupメンバー/ボリュームの最小サイズは100GiBです。
* FlexGroupボリュームではクローニングはサポートされていません。


FlexGroupとFlexGroupに適したワークロードについては、を参照してください https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroupボリュームベストプラクティスおよび実装ガイド"^]。

同じ環境で高度な機能と大規模な拡張性を実現するために 'ONTAP-NAS' を使用して Docker Volume Plugin の複数のインスタンスを実行し ' もう 1 つは「 ONTAP-NAS-エコノミー 」を使用して実行できます



=== Trident用のカスタムONTAPロール

Tridentで処理を実行するためにONTAP adminロールを使用する必要がないように、最小Privilegesを持つONTAPクラスタロールを作成できます。Tridentバックエンド構成にユーザ名を含めると、Trident作成したONTAPクラスタロールが使用されて処理が実行されます。

Tridentカスタムロールの作成の詳細については、を参照してくださいlink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Tridentカスタムロールジェネレータ"]。

[role="tabbed-block"]
====
.ONTAP CLIノシヨウ
--
. 次のコマンドを使用して新しいロールを作成します。
+
`security login role create <role_name\> -cmddirname "command" -access all –vserver <svm_name\>`

. Tridentユーザのユーザ名を作成します。
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`

. ユーザにロールをマッピングします。
+
`security login modify username <user_name\> –vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.System Managerの使用
--
ONTAPシステムマネージャで、次の手順を実行します。

. *カスタムロールの作成*：
+
.. クラスタレベルでカスタムロールを作成するには、*[クラスタ]>[設定]*を選択します。
+
（または）SVMレベルでカスタムロールを作成するには、*[ストレージ]>[Storage VM]>[設定]>[ユーザとロール]*を選択し `required SVM`ます。

.. [ユーザとロール]*の横にある矢印アイコン（*->*）を選択します。
.. [Roles]*で[+Add]*を選択します。
.. ロールのルールを定義し、*[保存]*をクリックします。


. *ロールをTridentユーザにマップする*:+[ユーザとロール]ページで次の手順を実行します。
+
.. [ユーザー]*で[アイコンの追加]*+*を選択します。
.. 必要なユーザ名を選択し、* Role *のドロップダウンメニューでロールを選択します。
.. [ 保存（ Save ） ] をクリックします。




--
====
詳細については、次のページを参照してください。

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["ONTAPの管理用のカスタムロール"^]またはlink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["カスタムロールの定義"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["ロールとユーザを使用する"^]




=== ONTAP 構成ファイルの例

.<code>ontap-nas</code> ドライバのNFSの例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.<code>ontap-nas-flexgroup</code> ドライバのNFSの例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.<code>ontap-nas-economy</code> ドライバのNFSの例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
====
.<code>ontap-san</code> ドライバのiSCSIの例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.<code>ontap-san-economy</code> ドライバのNFSの例
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.<code>ontap-san</code> ドライバのNVMe/TCPの例
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username":"vsadmin",
  "password":"password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.SCSI-SAN <code> ONTAP </code>ドライバの例
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username":"vsadmin",
  "password":"password",
  "useREST": true
}
----
====


== Element ソフトウェアの設定

Element ソフトウェア（ NetApp HCI / SolidFire ）を使用する場合は、グローバルな設定値のほかに、以下のオプションも使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「エンドポイント」  a| 
\ https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\ https://admin:admin@192.168.160.3/json-rpc/8.0



| 「 VIP 」  a| 
iSCSI の IP アドレスとポート
 a| 
10.0.0.7 ： 3260



| 「 tenantname 」  a| 
使用する SolidFire テナント（見つからない場合に作成）
 a| 
`docker`



| 「 InitiatorIFCace 」  a| 
iSCSI トラフィックをデフォルト以外のインターフェイスに制限する場合は、インターフェイスを指定します
 a| 
`default`



| 「タイプ」  a| 
QoS の仕様
 a| 
以下の例を参照してください



| 「 LegacyNamePrefix 」のように入力します  a| 
アップグレードされた Trident インストールのプレフィックス。1.3.2より前のバージョンのTridentを使用していて、既存のボリュームでアップグレードを実行した場合は、volume-nameメソッドでマッピングされた古いボリュームにアクセスするためにこの値を設定する必要があります。
 a| 
`netappdvp-`

|===
「 olidfire -san 」ドライバは Docker Swarm をサポートしていません。



=== Element ソフトウェア構成ファイルの例

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----