---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'ボリュームを作成するには、必要に応じてTridentドライバ名を指定して標準コマンドを使用し `docker volume`ます。' 
---
= ボリュームを操作します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じてTridentドライバ名を指定した標準コマンドを使用すると、ボリュームの作成、クローニング、および削除を簡単に実行でき `docker volume`ます。



== ボリュームを作成します

* デフォルトの名前を使用して、ドライバでボリュームを作成します。
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* 特定のTridentインスタンスを使用してボリュームを作成します。
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: 何も指定しない場合 link:volume-driver-options.html["オプション（ Options ）"^]、ドライバのデフォルトが使用されます。

* デフォルトのボリュームサイズを上書きします。ドライバーを使用して20 GiBのボリュームを作成するには、次の例を参照してください。
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: ボリュームサイズは、オプションの単位（ 10G 、 20GB 、 3TiB など）を含む整数値で指定します。単位を指定しない場合、デフォルトは g ですサイズの単位は、 2 の累乗（ B 、 KiB 、 MiB 、 GiB 、 TiB ）または 10 の累乗（ B 、 KB 、 MB 、 GB 、 TB ）のいずれかです。略記単位では、 2 の累乗が使用されます（ G=GiB 、 T=TiB 、…）。





== ボリュームを削除します

* 他の Docker ボリュームと同様にボリュームを削除します。
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: 「 olidfire -san 」ドライバを使用する場合、上記の例ではボリュームを削除してパージします。



Trident for Dockerをアップグレードするには、次の手順を実行します。



== ボリュームのクローンを作成します

、 `ontap-san` `solidfire-san`、、およびを `gcp-cvs storage drivers`使用する場合 `ontap-nas`、Tridentはボリュームをクローニングできます。ドライバまたは `ontap-nas-economy`ドライバを使用している場合、 `ontap-nas-flexgroup`クローニングはサポートされません。既存のボリュームから新しいボリュームを作成すると、新しい Snapshot が作成されます。

* ボリュームを調べて Snapshot を列挙します。
+
[source, console]
----
docker volume inspect <volume_name>
----
* 既存のボリュームから新しいボリュームを作成します。その結果、新しい Snapshot が作成されます。
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* ボリューム上の既存の Snapshot から新しいボリュームを作成します。新しい Snapshot は作成されません。
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 例

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 外部で作成されたボリュームにアクセス

外部で作成したブロックデバイス（またはそのクローン）には、パーティションがなく、ファイルシステムがTridentでサポートされている場合（例：-formatted `/dev/sdc1`はTrident経由でアクセスできません）にのみ、Trident *を使用してコンテナからアクセスできます `ext4`。
