---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: ストレージドライバにはそれぞれ異なるオプションがあり、ボリュームの作成時に指定することで結果をカスタマイズできます。構成済みのストレージシステムに適用されるオプションについては、以下を参照してください。 
---
= ドライバ固有のボリュームオプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージドライバにはそれぞれ異なるオプションがあり、ボリュームの作成時に指定することで結果をカスタマイズできます。構成済みのストレージシステムに適用されるオプションについては、以下を参照してください。

ボリューム作成処理では、これらのオプションを簡単に使用できます。CLI の操作中に '-o' 演算子を使用して ' オプションと値を指定しますこれらは、 JSON 構成ファイルの同等の値よりも優先されます。



== ONTAP ボリュームのオプション

NFS、iSCSI、およびFCのボリューム作成オプションには、次のものがあります。

[cols="2*"]
|===
| オプション | 説明 


| 「 size 」  a| 
ボリュームのサイズ。デフォルトは 1GiB です。



| 「平和のための準備」を参照してください  a| 
ボリュームをシンプロビジョニングまたはシックプロビジョニングします。デフォルトはシンです。有効な値は 'none( シン・プロビジョニング ) と 'volume( シック・プロビジョニング ) です



| 「ナプショットポリシー」  a| 
Snapshot ポリシーが目的の値に設定されます。デフォルトはで、 `none`ボリュームのSnapshotは自動的に作成されません。ストレージ管理者が変更しないかぎり、「default」というポリシーは、毎時6個、日次2個、週次2個のSnapshotを作成および保持するすべてのONTAPシステムに存在します。ボリューム内の任意のディレクトリを参照することで、Snapshotに保存されているデータをリカバリでき `.snapshot`ます。



| 「スナップショット予約」  a| 
これにより、 Snapshot リザーブの割合が希望する値に設定されます。デフォルト値は no で、 Snapshot ポリシーを選択した場合は ONTAP によって snapshotReserve が選択されます（通常は 5% ）。 Snapshot ポリシーがない場合は 0% が選択されます。構成ファイルのすべての ONTAP バックエンドに対して snapshotReserve のデフォルト値を設定できます。また、この値は、 ONTAP-NAS-エコノミー を除くすべての ONTAP バックエンドでボリューム作成オプションとして使用できます。



| 'plitOnClone  a| 
ボリュームをクローニングすると、そのクローンが原因 ONTAP によって親から即座にスプリットされます。デフォルトはです `false`。クローンボリュームのクローニングは、作成直後に親からクローンをスプリットする方法を推奨します。これは、ストレージ効率化の効果がまったくないためです。たとえば、空のデータベースをクローニングしても時間は大幅に短縮されますが、ストレージはほとんど削減されません。そのため、クローンはすぐにスプリットすることを推奨します。



| 「暗号化」  a| 
新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトは「false」です。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

バックエンドでNAEが有効になっている場合、TridentでプロビジョニングされたすべてのボリュームでNAEが有効になります。

詳細については、を参照してくださいlink:../trident-reco/security-reco.html["TridentとNVEおよびNAEとの連携"]。



| 階層ポリシー  a| 
ボリュームに使用する階層化ポリシーを設定します。これにより、アクセス頻度の低いコールドデータをクラウド階層に移動するかどうかが決まります。

|===
以下は、 NFS * のみ * 用の追加オプションです。

[cols="2*"]
|===
| オプション | 説明 


| 「 unixPermissions 」  a| 
これにより、ボリューム自体の権限セットを制御できます。デフォルトでは ' アクセス権は '--rwxr-xr-x' または数値表記 0755 に設定され 'root' は所有者になりますテキスト形式または数値形式のどちらかを使用できます。



| 「スナップショット方向」  a| 
これをに設定します `true` がを作成します `.snapshot` ボリュームにアクセスしているクライアントから認識できるディレクトリ。デフォルト値はです `false`の可視性を意味します `.snapshot` ディレクトリはデフォルトで無効になっています。一部のイメージ（公式のMySQLイメージなど）が、 `.snapshot` ディレクトリが表示されます。



| 「 exportPolicy 」と入力します  a| 
ボリュームで使用するエクスポートポリシーを設定します。デフォルトは「デフォルト」です。



| 'ecurityStyle'  a| 
ボリュームへのアクセスに使用するセキュリティ形式を設定します。デフォルトは「 unix 」です。有効な値は「 unix 」と「 immimixed 」です。

|===
以下の追加オプションは、 iSCSI * のみ * 用です。

[cols="2*"]
|===
| オプション | 説明 


| 「 filesystemtype 」です | iSCSI ボリュームのフォーマットに使用するファイルシステムを設定します。デフォルトは「 ext4 」です。有効な値は「 ext3 」、「 ext4 」、「 xfs 」です。 


| 「平和の配分」 | これをに設定します `false` LUNのスペース割り当て機能を無効にします。デフォルト値はです `true`つまり、ボリュームのスペースが不足し、ボリューム内のLUNに書き込みを受け付けられなくなったときに、ONTAP からホストに通知されます。また、このオプションで ONTAP 、ホストでデータが削除された時点での自動スペース再生も有効になります。 
|===


=== 例

以下の例を参照してください。

* 10 GiB のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* スナップショット付きの 100 GiB ボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* setuid ビットが有効になっているボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小ボリュームサイズは 20 MiB です。

スナップショット予約が指定されておらず、スナップショットポリシーがの場合、 `none`Tridentは0%のスナップショット予約を使用します。

* Snapshot ポリシーがなく、 Snapshot リザーブがないボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* Snapshot ポリシーがなく、カスタムの Snapshot リザーブが 10% のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* Snapshot ポリシーを使用し、カスタムの Snapshot リザーブを 10% に設定してボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* Snapshotポリシーを使用してボリュームを作成し、ONTAPのデフォルトのSnapshotリザーブ（通常は5%）をそのまま使用します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element ソフトウェアのボリュームオプション

Element ソフトウェアのオプションでは、ボリュームに関連付けられているサービス品質（ QoS ）ポリシーのサイズと QoS を指定できます。ボリュームが作成されると '-o type=service_level' という命名法を使用して ' ボリュームに関連付けられた QoS ポリシーが指定されます

Element ドライバを使用して QoS サービスレベルを定義する最初の手順は、少なくとも 1 つのタイプを作成し、構成ファイル内の名前に関連付けられた最小 IOPS 、最大 IOPS 、バースト IOPS を指定することです。

Element ソフトウェアのその他のボリューム作成オプションは次のとおりです。

[cols="2*"]
|===
| オプション | 説明 


| 「 size 」  a| 
ボリュームのサイズ。デフォルトは 1 GiB または構成エントリ...「defaults」: {"size": "5G"}。



| 「ブロックサイズ」  a| 
512 または 4096 のいずれかを使用します。デフォルトは 512 または config エントリ DefaultBlockSize です。

|===


=== 例

QoS 定義を含む次のサンプル構成ファイルを参照してください。

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
上記の構成では、 Bronze 、 Silver 、 Gold の 3 つのポリシー定義を使用します。これらの名前は任意です。

* 10 GiB のゴールド ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 100 GiB の Bronze ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

