---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  versions:
  - version-number: '23.10'
    url: "/trident"
  - version-number: '23.07'
    url: "/trident-2307"
  - version-number: '23.04'
    url: "/trident-2304"
  - version-number: '23.01'
    url: "/trident-2301"
  - version-number: '22.10'
    url: "/trident-2210"
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Trident のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/trident-rn.html"
    - title: 以前のバージョン
      url: "/earlier-versions.html"
  - section: trident-get-started
  - section: trident-install
  - section: trident-use
  - section: trident-managing-k8s
  - section: trident-docker
  - section: trident-reco
  - title: 知識とサポート
    entries:
    - title: よくある質問です
      url: "/faq.html"
    - title: トラブルシューティング
      url: "/troubleshooting.html"
    - title: ヘルプを表示します
      url: "/get-help.html"
  - section: trident-reference
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
