---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP NAS ドライバを使用した ONTAP バックエンドの設定について説明します。 
---
= ONTAP NASドライバの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP および Cloud Volumes ONTAP の NAS ドライバを使用した ONTAP バックエンドの設定について説明します。



== ONTAP NASドライバの詳細

Tridentは、ONTAPクラスタと通信するための次のNASストレージドライバを提供します。サポートされているアクセスモードは、_ReadWriteOnce_(RWO)、_ReadOnlyMany_(ROX)、_ReadWriteMany_(RWX)、_ReadWriteOncePod_(RWOP)です。

[cols="2, 1, 1, 2, 2"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされるファイルシステム 


| 「 ONTAP - NAS 」  a| 
NFS
SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs`、 `smb`



| 「 ONTAP - NAS - エコノミー」  a| 
NFS
SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs`、 `smb`



| 「 ONTAP-NAS-flexgroup 」  a| 
NFS
SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs`、 `smb`

|===
[WARNING]
====
* 使用 `ontap-san-economy` 永続的ボリュームの使用数が次の値よりも多いと予想される場合のみ link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^]。
* 使用 `ontap-nas-economy` 永続的ボリュームの使用数が次の値よりも多いと予想される場合のみ link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^] および `ontap-san-economy` ドライバは使用できません。
* 使用しないでください `ontap-nas-economy` データ保護、ディザスタリカバリ、モビリティのニーズが予想される場合。


====


== ユーザ権限

Tridentは、ONTAP管理者またはSVM管理者（通常はクラスタユーザ、 `vsadmin`SVMユーザ、または別の名前で同じロールのユーザを使用）として実行することを想定しています `admin`。

Amazon FSx for NetApp ONTAP環境では、Tridentは、クラスタユーザまたは `vsadmin`SVMユーザを使用するONTAP管理者またはSVM管理者、または同じロールの別の名前のユーザとして実行される必要があります `fsxadmin`。この `fsxadmin`ユーザは、クラスタ管理者ユーザに代わる限定的なユーザです。


NOTE: パラメータを使用する場合は `limitAggregateUsage`、クラスタ管理者の権限が必要です。TridentでAmazon FSx for NetApp ONTAPを使用している場合、 `limitAggregateUsage`パラメータはユーザアカウントと `fsxadmin`ユーザアカウントでは機能しません `vsadmin`。このパラメータを指定すると設定処理は失敗します。

ONTAP内でTridentドライバが使用できる、より制限の厳しいロールを作成することは可能ですが、推奨しません。Trident の新リリースでは、多くの場合、考慮すべき API が追加で必要になるため、アップグレードが難しく、エラーも起こりやすくなります。
