---
sidebar: sidebar 
permalink: trident-use/trident-nvme-rwx-subsystem-limits.html 
keywords: trident, nvme, rwx, ontap, nvme subsystem, rwx nvme limit, super-subsystem, controller limit, 26.02 
summary: ボリュームあたりの 64 ノード制限、サブシステム アーキテクチャの変更、必要なアップグレード手順など、RWX NVMe サブシステムの制限について説明します。 
---
= RWX NVMe サブシステムの制限について
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe プロトコルを使用する ReadWriteMany（RWX）ボリュームには、ボリュームあたり 64 ノードのスケーラビリティ制限があります。以下では、制限事項、関連する NVMe サブシステム アーキテクチャの説明、および必要な解決手順の概要を示します。



== 64ノードの制限について理解する

NVMe プロトコルで ReadWriteMany（RWX）ボリュームを使用する場合、単一の RWX NVMe ボリュームを Kubernetes クラスター内の 64 を超えるノードでマウントすることはできません。

同じRWX NVMe PersistentVolumeClaimをマウントするワークロードを64を超えるノードにわたってスケジュールしないでください。

この制限は、NVMe プロトコルを使用する RWX ボリュームにのみ適用されます。



== NVMe サブシステム モデルを理解する



=== ボリュームごとのサブシステムモデル（Trident 26.02より前のリリース）

Trident 26.02 より前のリリースでは、RWX NVMe ボリュームはボリュームごとのサブシステム モデルを使用してプロビジョニングされます。各 RWX NVMe ボリュームは、ONTAP 上の専用の NVMe サブシステムにマッピングされます。

このモデルはシンプルですが、スケーラビリティの制限は低くなります。大規模な Kubernetes クラスタでは、各 RWX ボリュームが専用のサブシステムを消費するため、サブシステム コントローラの制限にすぐに達します。



=== スーパーサブシステムモデル（Trident 26.02で導入）

Trident 26.02 以降、RWX NVMe ボリュームは共有スーパーサブシステム モデルを使用します。複数の RWX NVMe ボリュームが同じ NVMe サブシステムを共有します。

各スーパーサブシステムは最大 1024 個の名前空間（ボリューム）をサポートします。このモデルは RWX ワークロードのスケーラビリティを大幅に向上させ、ONTAP サブシステムの制限に達する可能性を低減します。

各 RWX NVMe ボリュームは最大 64 個のノードをサポートします。



== エラーの症状を特定する

RWX NVMe ボリュームを大規模に作成または接続すると、次のようなエラーが発生することがあります：

[listing]
----
Maximum number of controllers reached. No more controllers can be created.
----
このエラーは、ONTAP NVMe サブシステム コントローラの制限に達したことを示しています。



== サブシステム制限エラーを解決する

ボリュームごとのサブシステムの制限を超えてスーパーサブシステムモデルを活用するには、Trident 26.02以降にアップグレードしてください。



== Tridentをアップグレードしてスーパーサブシステムモデルを適用する

RWX NVMe ボリュームにスーパーサブシステム モデルを適用するには：

. Trident をバージョン 26.02 以降にアップグレードしてください。
. RWX NVMe ボリュームを使用するすべてのポッドをゼロレプリカにスケールダウンします。
. RWX NVMe ボリュームをアクティブに使用しているワークロードがないことを確認します。
. ポッドをスケールアップし直します。


この再起動シーケンスにより、RWX NVMe ボリュームがスーパーサブシステム モデルを使用して接続されます。

* この制限は、NVMe プロトコルを使用する RWX ボリュームにのみ適用されます。
* RWX NVMe ボリュームごとに 64 ノードの制限が適用されます。
* 他のアクセス モードおよび他のプロトコルは影響を受けません。

