---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: TridentとAmazon FSx for NetApp ONTAPを併用すると、Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタで、ONTAPを基盤とするブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。 
---
= Trident をインストール
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentは、KubernetesでAmazon FSx for NetApp ONTAPストレージ管理を合理化し、開発者や管理者がアプリケーションの導入に集中できるようにします。

次のいずれかの方法でTridentをインストールできます。

* Helm
* EKSアドオン


スナップショット機能を利用する場合は、CSIスナップショットコントローラアドオンをインストールします。詳細については、を参照してください link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["CSIボリュームのスナップショット機能を有効にする"^] 。



== Helmを使用したTridentのインストール

[role="tabbed-block"]
====
.ポッドのアイデンティティ
--
. NetApp Trident リポジトリを helm 構成に追加します。
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 次の例を使用して Trident をインストールします。
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
コマンドを使用して、名前、ネームスペース、グラフ、ステータス、アプリケーションのバージョン、リビジョン番号など、インストールの詳細を確認できます `helm list`。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.サービス アカウント アソシエーション (IRSA)
--
. NetApp Trident リポジトリを helm 構成に追加します。
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. *クラウド プロバイダー* と *クラウド ID* の値を設定します。
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
コマンドを使用して、名前、ネームスペース、グラフ、ステータス、アプリケーションのバージョン、リビジョン番号など、インストールの詳細を確認できます `helm list`。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
iSCSI を使用する場合は、クライアントマシンで iSCSI が有効になっていることを確認してください。AL2023Worker node OS を使用している場合は、helm インストール時に node prep パラメータを追加することで、iSCSI クライアントのインストールを自動化できます。

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== EKSアドオンを使用してTridentをインストールする

Trident EKSアドオンには、最新のセキュリティパッチ、バグ修正が含まれており、AWSによってAmazon EKSと連携することが検証されています。EKSアドオンを使用すると、Amazon EKSクラスタの安全性と安定性を一貫して確保し、アドオンのインストール、構成、更新に必要な作業量を削減できます。



=== 前提条件

AWS EKS用のTridentアドオンを設定する前に、次の条件を満たしていることを確認してください。

* アドオンサブスクリプションがあるAmazon EKSクラスタアカウント
* AWS MarketplaceへのAWS権限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMIタイプ：Amazon Linux 2（AL2_x86_64）またはAmazon Linux 2 Arm（AL2_ARM_64）
* ノードタイプ：AMDまたはARM
* 既存のAmazon FSx for NetApp ONTAPファイルシステム




=== AWS向けTridentアドオンを有効にする

[role="tabbed-block"]
====
.管理コンソール
--
. でAmazon EKSコンソールを開きます https://console.aws.amazon.com/eks/home#/clusters[]。
. 左側のナビゲーションペインで、*[クラスタ]*を選択します。
. NetApp Trident CSIアドオンを設定するクラスタの名前を選択します。
. *アドオン*を選択し、*追加のアドオン*を選択します。
. アドオンを選択するには、次の手順に従います。
+
.. *AWS Marketplace アドオン* セクションまでスクロールし、検索ボックスに *「Trident」* と入力します。
.. Trident by NetApp ボックスの右上隅にあるチェックボックスを選択します。
.. 「 * 次へ * 」を選択します。


. [Configure selected add-ons* settings]ページで、次の手順を実行します。
+
.. 使用する*バージョン*を選択します。
.. IRSA 認証を使用している場合は、オプション構成設定で使用可能な構成値を必ず設定してください。
+
*** 使用する*バージョン*を選択します。
*** *アドオン構成スキーマ* に従って、*構成値* セクションの *configurationValues* パラメータを、前の手順で作成した role-arn に設定します (値は次の形式である必要があります)。




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'"

}
----
+
[Conflict resolution method]で[Override]を選択すると、既存のアドオンの1つ以上の設定をAmazon EKSアドオン設定で上書きできます。このオプションを有効にしない場合、既存の設定と競合すると、操作は失敗します。表示されたエラーメッセージを使用して、競合のトラブルシューティングを行うことができます。このオプションを選択する前に、Amazon EKSアドオンが自己管理に必要な設定を管理していないことを確認してください。

. [次へ]*を選択します。
. [確認して追加]ページで、*[作成]*を選択します。
+
アドオンのインストールが完了すると、インストールされているアドオンが表示されます。



--
.AWS CLI
--
*1.作成する `add-on.json`ファイル*：

*Pod Identity の場合は、次の形式を使用します*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.02.1-eksbuild.1",
}
----
*IRSA 認証の場合は、次の形式を使用します*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.02.1-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: を、前の手順で作成したロールのARNに置き換えます `<role ARN>`。

*2.Trident EKS アドオンをインストールします。*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
次の例では、Trident EKSアドオンをインストールします。

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Trident EKSアドオンの更新

[role="tabbed-block"]
====
.管理コンソール
--
. Amazon EKSコンソールを開き https://console.aws.amazon.com/eks/home#/clusters[]ます。
. 左側のナビゲーションペインで、*[クラスタ]*を選択します。
. NetApp Trident CSIアドオンを更新するクラスタの名前を選択します。
. [アドオン]タブを選択します。
. Trident by NetApp *を選択し、* Edit *を選択します。
. [Configure Trident by NetApp *]ページで、次の手順を実行します。
+
.. 使用する*バージョン*を選択します。
.. [Optional configuration settings]*を展開し、必要に応じて変更します。
.. 「変更を保存」を選択します。




--
.AWS CLI
--
次の例では、EKSアドオンを更新します。

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.02.1-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* お使いのFSxN Trident CSIアドオンの現在のバージョンを確認してください。をクラスタ名に置き換え `my-cluster`ます。
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*出力例：*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.02.1-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 前の手順の出力でupdate availableで返されたバージョンにアドオンを更新します。
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.02.1-eksbuild.1 --cluster my-cluster --force
----


オプションを削除し、いずれかのAmazon EKSアドオン設定が既存の設定と競合している場合 `--force` 、Amazon EKSアドオンの更新は失敗します。競合の解決に役立つエラーメッセージが表示されます。このオプションを指定する前に、管理する必要がある設定がAmazon EKSアドオンで管理されていないことを確認してください。これらの設定はこのオプションで上書きされます。この設定のその他のオプションの詳細については、を参照してください link:https://eksctl.io/usage/addons/["アドオン"]。Amazon EKS Kubernetesフィールド管理の詳細については、を参照してください link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubernetesフィールド管理"]。

--
====


=== Trident EKSアドオンのアンインストール/削除

Amazon EKSアドオンを削除するには、次の2つのオプションがあります。

* *クラスタにアドオンソフトウェアを保持*–このオプションを選択すると、Amazon EKSによる設定の管理が削除されます。また、Amazon EKSが更新を通知し、更新を開始した後にAmazon EKSアドオンを自動的に更新する機能も削除されます。ただし、クラスタ上のアドオンソフトウェアは保持されます。このオプションを選択すると、アドオンはAmazon EKSアドオンではなく自己管理型インストールになります。このオプションを使用すると、アドオンのダウンタイムは発生しません。アドオンを保持するには、コマンドのオプションをそのまま使用し `--preserve` ます。
* *クラスターからアドオンソフトウェアを完全に削除する*–NetAppは、クラスターに依存するリソースがない場合にのみ、クラスターからAmazon EKSアドオンを削除することを推奨します。コマンドからオプションを削除してアドオンを削除し `--preserve` `delete` ます。



NOTE: アドオンにIAMアカウントが関連付けられている場合、IAMアカウントは削除されません。

[role="tabbed-block"]
====
.管理コンソール
--
. でAmazon EKSコンソールを開きます https://console.aws.amazon.com/eks/home#/clusters[]。
. 左側のナビゲーションペインで、*[クラスタ]*を選択します。
. NetApp Trident CSIアドオンを削除するクラスタの名前を選択します。
. *アドオン*タブを選択し、* Trident by NetApp *を選択します。*
. 「 * 削除」を選択します。
. [Remove netapp_trident-operator confirmation]*ダイアログで、次の手順を実行します。
+
.. Amazon EKSでアドオンの設定を管理しないようにするには、*[クラスタに保持]*を選択します。クラスタにアドオンソフトウェアを残して、アドオンのすべての設定を自分で管理できるようにする場合は、この手順を実行します。
.. 「netapp_trident -operator *」と入力します。
.. 「 * 削除」を選択します。




--
.AWS CLI
--
をクラスタの名前に置き換え `my-cluster` 、次のコマンドを実行します。

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
次のコマンドは、Trident EKSアドオンをアンインストールします。

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====