---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: TridentとAmazon FSx for NetApp ONTAPを併用すると、Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタで、ONTAPを基盤とするブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。 
---
= Amazon FSx for NetApp ONTAPでTridentを使用
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^] は、NetApp ONTAP ストレージオペレーティングシステムを基盤とするファイルシステムの起動や実行を可能にする、フルマネージドのAWSサービスです。FSX for ONTAP を使用すると、使い慣れたネットアップの機能、パフォーマンス、管理機能を活用しながら、AWSにデータを格納するためのシンプルさ、即応性、セキュリティ、拡張性を活用できます。FSX for ONTAP は、ONTAP ファイルシステムの機能と管理APIをサポートしています。

Amazon FSx for NetApp ONTAPファイルシステムをTridentと統合すると、Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタが、ONTAPを基盤とするブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。

ファイルシステムは、オンプレミスの ONTAP クラスタに似た、 Amazon FSX のプライマリリソースです。各 SVM 内には、ファイルとフォルダをファイルシステムに格納するデータコンテナである 1 つ以上のボリュームを作成できます。Amazon FSx for NetApp ONTAPは、クラウドのマネージドファイルシステムとして提供されます。新しいファイルシステムのタイプは * NetApp ONTAP * です。

TridentとAmazon FSx for NetApp ONTAPを使用すると、Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタが、ONTAPを基盤とするブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。



== 要件

link:../trident-get-started/requirements.html["Tridentの要件"]FSx for ONTAPとTridentを統合するには、さらに次のものが必要です。

* 既存の Amazon EKS クラスタまたは 'kubectl' がインストールされた自己管理型 Kubernetes クラスタ
* クラスタのワーカーノードから到達可能な既存のAmazon FSx for NetApp ONTAPファイルシステムおよびStorage Virtual Machine（SVM）。
* 準備されているワーカーノード link:worker-node-prep.html["NFSまたはiSCSI"]。
+

NOTE: Amazon LinuxおよびUbuntuで必要なノードの準備手順を実行します https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine Images の略"^] （ AMIS ） EKS の AMI タイプに応じて異なります。





== 考慮事項

* SMBボリューム：
+
** SMBボリュームは、を使用してサポートされます `ontap-nas` ドライバーのみ。
** SMBボリュームは、Trident EKSアドオンではサポートされません。
** Tridentでは、Windowsノードで実行されているポッドにマウントされたSMBボリュームのみがサポートされます。詳細については、を参照してください link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["SMBボリュームをプロビジョニングする準備をします"] 。


* Trident 24.02より前のバージョンでは、自動バックアップが有効になっているAmazon FSxファイルシステム上に作成されたボリュームは、Tridentで削除できませんでした。Trident 24.02以降でこの問題を回避するには、AWS FSx for ONTAPのバックエンド構成ファイルで、 `apiRegion`AWS、AWS、およびAWS `apikey`を `secretKey`指定します `fsxFilesystemID`。
+

NOTE: TridentにIAMロールを指定する場合は、、 `apiKey`、および `secretKey`の各フィールドをTridentに明示的に指定する必要はありません `apiRegion`。詳細については、を参照してください link:../trident-use/trident-fsx-examples.html["FSX（ONTAP の構成オプションと例）"]。





== 認証

Tridentには2つの認証モードがあります。

* クレデンシャルベース（推奨）：クレデンシャルをAWS Secrets Managerに安全に格納します。ファイルシステムのユーザ、またはSVM用に設定されているユーザを使用できます `fsxadmin` `vsadmin` 。
+

WARNING: Tridentは、SVMユーザ、または別の名前で同じロールのユーザとして実行することを想定しています `vsadmin`。Amazon FSx for NetApp ONTAPには、ONTAPクラスタユーザに代わる限定的なユーザが `admin`い `fsxadmin`ます。Tridentでの使用を強くお勧めします `vsadmin`。

* 証明書ベース：Tridentは、SVMにインストールされている証明書を使用してFSxファイルシステム上のSVMと通信します。


認証を有効にする方法の詳細については、使用しているドライバタイプの認証を参照してください。

* link:ontap-nas-prep.html["ONTAP NAS認証"]
* link:ontap-san-prep.html["ONTAP SAN認証"]




== テスト済みのAmazonマシンイメージ（AMIS）

EKSクラスタはさまざまなオペレーティングシステムをサポートしていますが、AWSではコンテナとEKS用に特定のAmazon Machine Images（AMIS）が最適化されています。次のAMIはTrident 24.10でテストされています。

|===


| 亜美 | NAS | NASエコノミー | SAN | SANエコノミー 


| AL2023_x86_64_STANDARD | はい。 | はい。 | はい。 | はい。 


| AL2_x86_64 | はい。 | はい。 | はい** | はい** 


| BOTTLEROCKET_x86_64 | はい* | はい。 | N/A | N/A 


| AL2023_ARM_64_STANDARD | はい。 | はい。 | はい。 | はい。 


| AL2_ARM_64 | はい。 | はい。 | はい** | はい** 


| BOTTLEROCKET_ARM_64 | はい* | はい。 | N/A | N/A 
|===
* *マウントオプションでは「nolock」を使用する必要があります。
* **ノードを再起動せずにPVを削除できません



NOTE: 目的のAMIがここにリストされていない場合、サポートされていないという意味ではなく、単にテストされていないことを意味します。このリストは、動作が確認されているAMISのガイドとして機能します。

*テスト実施項目*：

* EKS version: 1.30
* インストール方法：HelmとAWSアドオンとして
* NASについては、NFSv3とNFSv4.1の両方をテストしました。
* SANについてはiSCSIのみをテストし、NVMe-oFはテストしませんでした。


*実行されたテスト*：

* 作成：ストレージクラス、PVC、POD
* 削除：ポッド、PVC（通常、qtree / LUN–エコノミー、NASとAWSバックアップ）




== 詳細については、こちらをご覧ください

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP のドキュメント"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Amazon FSX for NetApp ONTAP に関するブログ記事です"^]

