---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Tridentオペレータを導入し、Helmを使用してTridentをインストールできます。このプロセスは、Tridentに必要なコンテナイメージがプライベートレジストリに保存されているインストールに適用されます。 
---
= Helm（オフラインモード）を使用したTridentのオペレータの導入
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentオペレータを導入し、Helmを使用してTridentをインストールできます。このプロセスは、Tridentに必要なコンテナイメージがプライベートレジストリに保存されているインストールに適用されます。プライベートイメージレジストリがない場合は、を使用しlink:kubernetes-deploy-helm.html["標準的な導入のプロセス"]ます。



== Trident 25.06に関する重要な情報

* Tridentに関する次の重要な情報をお読みください。*

.Trident </strong>に関する<strong>の重要な情報
[%collapsible%open]
====
[]
=====
* TridentでKubernetes 1.33がサポートされるようになりました。Kubernetesをアップグレードする前にTridentをアップグレード
* Tridentでは、SAN環境でのマルチパス構成の使用が厳密に適用されます。multipath.confファイルの推奨値はです `find_multipaths: no`。
+
非マルチパス構成またはを使用 `find_multipaths: yes` または `find_multipaths: smart` multipath.confファイルの値が原因でマウントが失敗します。Tridentはの使用を推奨しています `find_multipaths: no` 21.07リリース以降



=====
====


== Tridentオペレータを導入し、Helmを使用してTridentをインストールする

Tridentの使用 link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Helmチャート"^] Tridentオペレータを導入し、Tridentを一度にインストールできます。

レビュー link:../trident-get-started/kubernetes-deploy.html["インストールの概要"] インストールの前提条件を満たし、環境に適したインストールオプションを選択していることを確認します。

.作業を開始する前に
に加えて link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["導入の前提条件"] 必要です link:https://v3.helm.sh/["Helm バージョン 3"^]。


IMPORTANT: プライベートリポジトリにTridentをインストールするときに、スイッチを使用してリポジトリの場所を指定する場合は `imageRegistry`、リポジトリパスにを使用しないで `/netapp/`ください。

.手順
. Trident Helmリポジトリを追加します。
+
[source, console]
----
helm repo add netapp-trident https://artifacthub.io/packages/helm/netapp-trident/trident-operator
----
. を使用し `helm install` 、展開とイメージレジストリの場所の名前を指定します。は link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["TridentとCSIの画像"] 1つのレジストリまたは別のレジストリに配置できますが、すべてのCSIイメージは同じレジストリに配置する必要があります。この例では、 `100.2506.0`はインストールするTridentのバージョンです。
+
[role="tabbed-block"]
====
.1つのレジストリ内のイメージ
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.異なるレジストリ内の画像
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.06.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.06 --set tridentImage=<your-registry>/trident:25.06.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: すでにTridentの名前空間を作成している場合'--create-namespaceパラメータは追加の名前空間を作成しません



を使用できます `helm list` 名前、ネームスペース、グラフ、ステータス、アプリケーションバージョンなどのインストールの詳細を確認するには、次の手順を実行します。とリビジョン番号。



== インストール中に設定データを渡す

インストール中に設定データを渡すには、次の 2 つの方法があります。

[cols="2"]
|===
| オプション | 説明 


| `--values` （または `-f`)  a| 
オーバーライドを使用してYAMLファイルを指定します。これは複数回指定でき、右端のファイルが優先されます。



| `--set`  a| 
コマンドラインでオーバーライドを指定します。

|===
たとえば、のデフォルト値を変更するには `debug`、次のコマンドを実行します。は、インストールするTridentのバージョンです。 `100.2506.0`

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
nodePrep値を追加するには、次のコマンドを実行します。

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== 設定オプション

このテーブルと `values.yaml` Helmチャートの一部であるファイルには、キーとそのデフォルト値のリストが表示されます。


WARNING: values.yamlファイルからデフォルトのアフィニティを削除しないでください。カスタムアフィニティを提供する場合は、デフォルトのアフィニティを拡張します。

[cols="3"]
|===
| オプション | 説明 | デフォルト 


| `nodeSelector` | ポッド割り当てのノードラベル |  


| `podAnnotations` | ポッドの注釈 |  


| `deploymentAnnotations` | 配置のアノテーション |  


| `tolerations` | ポッド割り当ての許容値 |  


| `affinity` | ポッド割り当てのアフィニティ  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: values.yamlファイルからデフォルトのアフィニティを削除しないでください。カスタムアフィニティを提供する場合は、デフォルトのアフィニティを拡張します。



| `tridentControllerPluginNodeSelector` | ポッド用の追加のノードセレクタ。を参照してください link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["コントローラポッドとノードポッドについて"] を参照してください。 |  


| `tridentControllerPluginTolerations` | ポッドに対するKubernetesの許容範囲を上書きします。を参照してください link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["コントローラポッドとノードポッドについて"] を参照してください。 |  


| `tridentNodePluginNodeSelector` | ポッド用の追加のノードセレクタ。を参照してください link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["コントローラポッドとノードポッドについて"] を参照してください。 |  


| `tridentNodePluginTolerations` | ポッドに対するKubernetesの許容範囲を上書きします。を参照してください link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["コントローラポッドとノードポッドについて"] を参照してください。 |  


| 「 imageRegistry 」と入力します | 、、 `trident`およびその他のイメージのレジストリを指定します `trident-operator`。デフォルトをそのまま使用する場合は、空のままにします。重要：プライベートリポジトリにTridentをインストールする場合、スイッチを使用してリポジトリの場所を指定する場合は `imageRegistry`、リポジトリパスにはを使用しないで `/netapp/`ください。 | "" 


| `imagePullPolicy` | のイメージプルポリシーを設定します `trident-operator`。 | `IfNotPresent` 


| 「 imagePullSecrets 」 | のイメージプルシークレットを設定します `trident-operator`、 `trident`、およびその他の画像。 |  


| 「 kubeletDir 」を参照してください | kubeletの内部状態のホスト位置を上書きできます。 | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Tridentオペレータのログレベルを次のように設定できます。 `trace`、 `debug`、 `info`、 `warn`、 `error`または `fatal`。 | `"info"` 


| `operatorDebug` | Tridentオペレータのログレベルをdebugに設定できます。 | 「真」 


| `operatorImage` | のイメージを完全に上書きできます `trident-operator`。 | "" 


| `operatorImageTag` | のタグを上書きできます `trident-operator` イメージ（Image）： | "" 


| `tridentIPv6` | IPv6クラスタでのTridentの動作を有効にできます。 | 「偽」 


| `tridentK8sTimeout` | ほとんどのKubernetes API処理でデフォルトの30秒タイムアウトを上書きします（0以外の場合は秒単位）。 | `0` 


| `tridentHttpRequestTimeout` | HTTP要求のデフォルトの90秒タイムアウトをで上書きします `0s` タイムアウトの期間は無限です。負の値は使用できません。 | `"90s"` 


| `tridentSilenceAutosupport` | Trident定期AutoSupportレポートをディセーブルにできます。 | 「偽」 


| `tridentAutosupportImageTag` | Trident AutoSupportコンテナのイメージのタグを上書きできます。 | `<version>` 


| `tridentAutosupportProxy` | Trident AutoSupportコンテナがHTTPプロキシ経由で自宅に電話できるようにします。 | "" 


| `tridentLogFormat` | Tridentロギング形式を設定し(`text`ます。または `json`） | `"text"` 


| `tridentDisableAuditLog` | Trident監査ロガーをディセーブルにします。 | 「真」 


| `tridentLogLevel` | Tridentのログレベルを、、 `debug` `info`、、 `warn`、 `error`または `fatal`に設定 `trace`できます。 | `"info"` 


| `tridentDebug` | Tridentのログレベルをに設定できます `debug`。 | 「偽」 


| `tridentLogWorkflows` | 特定のTridentワークフローのトレースロギングまたはログ抑制を有効にできます。 | "" 


| `tridentLogLayers` | トレースロギングまたはログ抑制に対して特定のTridentレイヤをイネーブルにできます。 | "" 


| 「 tridentImage 」のように入力します | Tridentのイメージを完全に上書きできます。 | "" 


| `tridentImageTag` | Tridentのイメージのタグを上書きできます。 | "" 


| `tridentProbePort` | Kubernetesの活性/準備プローブに使用されるデフォルトポートを上書きできます。 | "" 


| `windows` | TridentをWindowsワーカーノードにインストールできるようにします。 | 「偽」 


| `enableForceDetach` | 強制切り離し機能を有効にできます。 | 「偽」 


| `excludePodSecurityPolicy` | オペレータポッドのセキュリティポリシーを作成から除外します。 | 「偽」 


| `nodePrep` | 指定したデータストレージプロトコルを使用してボリュームを管理できるように、TridentでKubernetesクラスタのノードを準備できるようにします。*現在 `iscsi`サポートされている値は、のみです。* |  
|===