---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Tridentオペレータを導入し、Helmを使用してTridentをインストールできます。このプロセスは、Tridentに必要なコンテナイメージがプライベートレジストリに保存されていないインストールに適用されます。 
---
= Helm（標準モード）を使用してTridentを導入
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentオペレータを導入し、Helmを使用してTridentをインストールできます。このプロセスは、Tridentに必要なコンテナイメージがプライベートレジストリに保存されていないインストールに適用されます。プライベートイメージレジストリがある場合は、を使用しlink:kubernetes-deploy-helm-mirror.html["オフライン導入のプロセス"]ます。



== Trident 25.10に関する重要な情報

* Tridentに関する次の重要な情報をお読みください。*

.Trident </strong>に関する<strong>の重要な情報
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 がTridentでサポートされるようになりました。Kubernetes をアップグレードする前にTridentをアップグレードします。
* Tridentでは、SAN環境でのマルチパス構成の使用が厳密に適用されます。multipath.confファイルの推奨値はです `find_multipaths: no`。
+
非マルチパス構成またはを使用 `find_multipaths: yes` または `find_multipaths: smart` multipath.confファイルの値が原因でマウントが失敗します。Tridentはの使用を推奨しています `find_multipaths: no` 21.07リリース以降



=====
====


== Tridentオペレータを導入し、Helmを使用してTridentをインストールする

Tridentの使用 link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Helmチャート"^] Tridentオペレータを導入し、Tridentを一度にインストールできます。

レビュー link:../trident-get-started/kubernetes-deploy.html["インストールの概要"] インストールの前提条件を満たし、環境に適したインストールオプションを選択していることを確認します。

.作業を開始する前に
に加えて link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["導入の前提条件"] 必要です link:https://v3.helm.sh/["Helm バージョン 3"^]。

.手順
. Trident Helmリポジトリを追加します。
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. を使用し `helm install`、次の例のように導入環境の名前を指定します。 `100.2506.0`は、インストールするTridentのバージョンです。
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: すでにTridentの名前空間を作成している場合'--create-namespaceパラメータは追加の名前空間を作成しません



を使用できます `helm list` 名前、ネームスペース、グラフ、ステータス、アプリケーションバージョンなどのインストールの詳細を確認するには、次の手順を実行します。とリビジョン番号。



== インストール中に設定データを渡す

インストール中に設定データを渡すには、次の 2 つの方法があります。

[cols="2"]
|===
| オプション | 説明 


| `--values` （または `-f`)  a| 
オーバーライドを使用してYAMLファイルを指定します。これは複数回指定でき、右端のファイルが優先されます。



| `--set`  a| 
コマンドラインでオーバーライドを指定します。

|===
たとえば、のデフォルト値を変更するには `debug`、次のコマンドを実行します。は、インストールするTridentのバージョンです。 `100.2506.0`

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== 設定オプション

このテーブルと `values.yaml` Helmチャートの一部であるファイルには、キーとそのデフォルト値のリストが表示されます。

[cols="1,2,3"]
|===
| オプション | 説明 | デフォルト 


| `nodeSelector` | ポッド割り当てのノードラベル |  


| `podAnnotations` | ポッドの注釈 |  


| `deploymentAnnotations` | 配置のアノテーション |  


| `tolerations` | ポッド割り当ての許容値 |  


| `affinity` | ポッド割り当てのアフィニティ  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: values.yamlファイルからデフォルトのアフィニティを削除しないでください。カスタムアフィニティを提供する場合は、デフォルトのアフィニティを拡張します。



| `tridentControllerPluginNodeSelector` | ポッド用の追加のノードセレクタ。を参照してください <<コントローラポッドとノードポッドについて>> を参照してください。 |  


| `tridentControllerPluginTolerations` | ポッドに対するKubernetesの許容範囲を上書きします。を参照してください <<コントローラポッドとノードポッドについて>> を参照してください。 |  


| `tridentNodePluginNodeSelector` | ポッド用の追加のノードセレクタ。を参照してください <<コントローラポッドとノードポッドについて>> を参照してください。 |  


| `tridentNodePluginTolerations` | ポッドに対するKubernetesの許容範囲を上書きします。を参照してください <<コントローラポッドとノードポッドについて>> を参照してください。 |  


| 「 imageRegistry 」と入力します | 、、 `trident`およびその他のイメージのレジストリを指定します `trident-operator`。デフォルトをそのまま使用する場合は、空のままにします。重要：プライベートリポジトリにTridentをインストールする場合、スイッチを使用してリポジトリの場所を指定する場合は `imageRegistry`、リポジトリパスにはを使用しないで `/netapp/`ください。 | `""` 


| `imagePullPolicy` | のイメージプルポリシーを設定します `trident-operator`。 | `IfNotPresent` 


| 「 imagePullSecrets 」 | のイメージプルシークレットを設定します `trident-operator`、 `trident`、およびその他の画像。 |  


| 「 kubeletDir 」を参照してください | kubeletの内部状態のホスト位置を上書きできます。 | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Tridentオペレータのログレベルを次のように設定できます。 `trace`、 `debug`、 `info`、 `warn`、 `error`または `fatal`。 | `"info"` 


| `operatorDebug` | Tridentオペレータのログレベルをdebugに設定できます。 | 「真」 


| `operatorImage` | のイメージを完全に上書きできます `trident-operator`。 | `""` 


| `operatorImageTag` | のタグを上書きできます `trident-operator` イメージ（Image）： | `""` 


| `tridentIPv6` | IPv6クラスタでのTridentの動作を有効にできます。 | 「偽」 


| `tridentK8sTimeout` | ほとんどのKubernetes API処理でデフォルトの30秒タイムアウトを上書きします（0以外の場合は秒単位）。 | `0` 


| `tridentHttpRequestTimeout` | HTTP要求のデフォルトの90秒タイムアウトをで上書きします `0s` タイムアウトの期間は無限です。負の値は使用できません。 | `"90s"` 


| `tridentSilenceAutosupport` | Trident定期AutoSupportレポートをディセーブルにできます。 | 「偽」 


| `tridentAutosupportImageTag` | Trident AutoSupportコンテナのイメージのタグを上書きできます。 | `<version>` 


| `tridentAutosupportProxy` | Trident AutoSupportコンテナがHTTPプロキシ経由で自宅に電話できるようにします。 | `""` 


| `tridentLogFormat` | Tridentロギング形式を設定し(`text`ます。または `json`） | `"text"` 


| `tridentDisableAuditLog` | Trident監査ロガーをディセーブルにします。 | 「真」 


| `tridentLogLevel` | Tridentのログレベルを、、 `debug` `info`、、 `warn`、 `error`または `fatal`に設定 `trace`できます。 | `"info"` 


| `tridentDebug` | Tridentのログレベルを次のように設定できます。 `debug` 。ノード ヘルス チェック (NHC) オペレーターとの統合により、強制デタッチ プロセスを自動化できます。詳細については、link:../trident-reco/force-detach.html["Tridentによるステートフル アプリケーションのフェイルオーバーの自動化"] 。 | 「偽」 


| `tridentLogWorkflows` | 特定のTridentワークフローのトレースロギングまたはログ抑制を有効にできます。 | `""` 


| `tridentLogLayers` | トレースロギングまたはログ抑制に対して特定のTridentレイヤをイネーブルにできます。 | `""` 


| 「 tridentImage 」のように入力します | Tridentのイメージを完全に上書きできます。 | `""` 


| `tridentImageTag` | Tridentのイメージのタグを上書きできます。 | `""` 


| `tridentProbePort` | Kubernetesの活性/準備プローブに使用されるデフォルトポートを上書きできます。 | `""` 


| `windows` | TridentをWindowsワーカーノードにインストールできるようにします。 | 「偽」 


| `enableForceDetach` | 強制切り離し機能を有効にできます。 | 「偽」 


| `excludePodSecurityPolicy` | オペレータポッドのセキュリティポリシーを作成から除外します。 | 「偽」 


| `cloudProvider` | をに設定します `"Azure"` AKSクラスタで管理対象IDまたはクラウドIDを使用する場合。EKSクラスタでクラウドIDを使用する場合は、「aws」に設定します。 | `""` 


| `cloudIdentity` | AKSクラスタでクラウドIDを使用する場合は、ワークロードID（「azure.workload.identity/client-id：xxxxxxxxxx-xxxx-xxxxxxx」）に設定します。EKSクラスタでクラウドIDを使用する場合は、AWS IAMロール（「eks.amazonaws.com/role-arn: arn：aws：iam：：123456：role / Trident -role」）に設定されます。 | `""` 


| `iscsiSelfHealingInterval` | iSCSIの自己修復が実行される間隔。 | `5m0s` 


| `iscsiSelfHealingWaitTime` | iSCSIの自己修復が、ログアウトとその後のログインを実行して古いセッションの解決を開始するまでの時間。 | `7m0s` 


| `nodePrep` | 指定されたデータ ストレージ プロトコルを使用してボリュームを管理するために、 Tridentが Kubernetes クラスターのノードを準備できるようにします。 *現在、 `iscsi`サポートされている唯一の値です。*注意: OpenShift 4.19 以降、この機能でサポートされるTrident の最小バージョンは 25.06.1 です。 |  


| `enableConcurrency`  a| 
スループットを向上させるために、同時Tridentコントローラー操作を有効にします。


NOTE: *テクニカル プレビュー*: この機能は実験段階であり、現在、ONTAP -SAN ドライバー (統合ONTAP 9 の iSCSI および FCP プロトコル) の既存のテクニカル プレビューに加えて、 ONTAP-NAS (NFS のみ) およびONTAP -SAN (統合ONTAP 9 のONTAP ) ドライバーを使用した限定的な並列ワークフローをサポートしています。
| いいえ 


| `k8sAPIQPS`  a| 
Kubernetes API サーバーと通信するときにコントローラーが使用する 1 秒あたりのクエリ数 (QPS) の制限。バースト値は QPS 値に基づいて自動的に設定されます。
| `100`; オプション 


| `resources`  a| 
Tridentコントローラー、ノード、オペレーター ポッドの Kubernetes リソース制限と要求を設定します。Kubernetes でのリソース割り当てを管理するために、コンテナとサイドカーごとに CPU とメモリを設定できます。

リソース要求と制限の設定の詳細については、以下を参照してください。link:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["ポッドとコンテナのリソース管理"^] 。

[WARNING]
====
* コンテナまたはフィールドの名前を変更しないでください。
* インデントを変更しないでください。YAML インデントは適切な解析に重要です。


====
[NOTE]
====
* デフォルトでは制限は適用されません。リクエストのみにデフォルト値があり、指定されていない場合は自動的に適用されます。
* コンテナ名は、ポッド仕様に表示されるとおりにリストされます。
* サイドカーは各メイン コンテナーの下にリストされます。
* TORCを確認する `status.CurrentInstallationParams`現在適用されている値を表示するフィールド。


==== a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----


| `httpsMetrics` | Prometheus メトリック エンドポイントに対して HTTPS を有効にします。 | いいえ 


| 「ホストネットワーク」  a| 
Tridentコントローラーのホスト ネットワークを有効にします。これは、マルチホーム ネットワークでフロントエンド トラフィックとバックエンド トラフィックを分離する場合に便利です。
| いいえ 
|===


=== コントローラポッドとノードポッドについて

Tridentは、単一のコントローラポッドと、クラスタ内の各ワーカーノード上のノードポッドとして動作します。Tridentボリュームをマウントする可能性があるホストでノードポッドが実行されている必要があります。

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["ノードセレクタ"^] および link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["寛容さと汚れ"^] は、特定のノードまたは優先ノードで実行されるようにポッドを制限するために使用されます。「ControllerPlugin」およびを使用します `NodePlugin`を使用すると、拘束とオーバーライドを指定できます。

* コントローラプラグインは、Snapshotやサイズ変更などのボリュームのプロビジョニングと管理を処理します。
* ノードプラグインによって、ノードへのストレージの接続が処理されます。

