---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Tridentをインストールする前に、これらの一般的なシステム要件を確認してください。個 々 のバックエンドには追加の要件がある場合があり 
---
= 要件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentをインストールする前に、これらの一般的なシステム要件を確認してください。個 々 のバックエンドには追加の要件がある場合があり



== Tridentに関する重要な情報

* Tridentに関する次の重要な情報をお読みください。*

.Trident </strong>に関する<strong>の重要な情報
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 がTridentでサポートされるようになりました。Kubernetes をアップグレードする前にTridentをアップグレードします。
* Tridentでは、SAN環境でのマルチパス構成の使用が厳密に適用されます。multipath.confファイルの推奨値はです `find_multipaths: no`。
+
非マルチパス構成またはを使用 `find_multipaths: yes` または `find_multipaths: smart` multipath.confファイルの値が原因でマウントが失敗します。Tridentはの使用を推奨しています `find_multipaths: no` 21.07リリース以降



=====
====


== サポートされるフロントエンド（オーケストレーションツール）

Tridentは、次のような複数のコンテナエンジンとオーケストレーションツールをサポートしています。

* Anthosオンプレミス（VMware）とAnthos（ベアメタル1.16）
* Kubernetes 1.27 - 1.34
* OpenShift 4.12、4.14 - 4.19 (OpenShift 4.19 で iSCSI ノードの準備を使用する場合、サポートされる最小Tridentバージョンは 25.06.1 です。)
+

NOTE: Tridentは、OpenShiftの古いバージョンを引き続きサポートします。link:https://access.redhat.com/support/policy/updates/openshift["Red Hat 延長アップデートサポート (EUS) リリースライフサイクル"]アップストリームで公式にサポートされなくなった Kubernetes バージョンに依存している場合でも同様です。このような場合、 Tridentをインストールするときに、Kubernetes バージョンに関する警告メッセージは無視しても問題ありません。

* Rancher Kubernetes Engine 2 (RKE2) v1.27.x - 1.34.x
+

NOTE: Tridentは Rancher Kubernetes Engine 2 (RKE2) バージョン 1.27.x - 1.34.x でサポートされていますが、 Tridentは現在 RKE2 v1.28.5+rke2r1 でのみ認定されています。_



Tridentは、Google Kubernetes Engine（GKE）、Amazon Elastic Kubernetes Services（EKS）、Azure Kubernetes Service（AKS）、Mirantis Kubernetes Engine（MKE）、VMware Tanzu Portfolioなど、他のフルマネージド/自己管理型Kubernetesソリューションとも連携します。

TridentとONTAPは、のストレージプロバイダとして使用できますlink:https://kubevirt.io/["KubeVirt"]。


WARNING: TridentがインストールされているKubernetesクラスタを1.25から1.26以降にアップグレードする前に、を参照してくださいlink:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Helmインストールのアップグレード"]。



== サポートされるバックエンド（ストレージ）

Tridentを使用するには、次のサポートされているバックエンドが1つ以上必要です。

* NetApp ONTAP 対応の Amazon FSX
* Azure NetApp Files の特長
* Cloud Volumes ONTAP
* Google Cloud NetAppボリューム
* ネットアップオール SAN アレイ（ ASA ）
* NetApp の限定サポートによるオンプレミスのFAS、 AFF、またはASA r2 (iSCSI、NVMe/TCP、および FC) クラスター バージョン。見るlink:https://mysupport.netapp.com/site/info/version-support["ソフトウェア バージョンのサポート"]。
* NetApp HCI / Elementソフトウェア11以降




== TridentによるKubeVirtとOpenShiftによる仮想化のサポート

.サポートされるストレージドライバ：
Tridentは、KubeVirtおよびOpenShift仮想化用に次のONTAPドライバをサポートしています。

* ONTAP - NAS
* ONTAP - NAS -エコノミー
* SAN-SAN（iSCSI、FCP、ONTAP over TCP）
* ONTAP SANエコノミー（iSCSIのみ）


.考慮すべきポイント：
* OpenShift仮想化環境でストレージクラスを更新し、パラメータ（例： `fsType: "ext4"`）を使用 `fsType`します。必要に応じて、のパラメータを `dataVolumeTemplates`使用してブロックデータボリュームの作成をCDIに通知し、ボリュームモードを明示的にブロックするように設定し `volumeMode=Block`ます。
* ブロックストレージドライバの_rwxアクセスモード_：ONTAP SAN（iSCSI、NVMe/TCP、FC）およびONTAP SANエコノミー（iSCSI）ドライバは、「volumeMode：Block」（rawデバイス）でのみサポートされます。これらのドライバでは `fstype`、ボリュームはrawデバイスモードで提供されるため、パラメータは使用できません。
* RWXアクセスモードが必要なライブマイグレーションワークフローでは、次の組み合わせがサポートされます。
+
** NFS + `volumeMode=Filesystem`
** iSCSI+ `volumeMode=Block`（rawデバイス）
** NVMe/TCP+ `volumeMode=Block`（rawデバイス）
** FC+ `volumeMode=Block`（rawデバイス）






== 機能の要件

次の表は、このリリースのTridentで使用できる機能と、このリリースでサポートされるKubernetesのバージョンをまとめたものです。

[cols="3"]
|===
| フィーチャー（ Feature ） | Kubernetes のバージョン | フィーチャーゲートが必要ですか？ 


| Trident  a| 
1.27 - 1.34
 a| 
いいえ



| ボリューム Snapshot  a| 
1.27 - 1.34
 a| 
いいえ



| ボリューム Snapshot からの PVC  a| 
1.27 - 1.34
 a| 
いいえ



| iSCSI PV のサイズ変更  a| 
1.27 - 1.34
 a| 
いいえ



| ONTAP 双方向 CHAP  a| 
1.27 - 1.34
 a| 
いいえ



| 動的エクスポートポリシー  a| 
1.27 - 1.34
 a| 
いいえ



| Trident のオペレータ  a| 
1.27 - 1.34
 a| 
いいえ



| CSI トポロジ  a| 
1.27 - 1.34
 a| 
いいえ

|===


== テスト済みのホストオペレーティングシステム

Tridentは特定のオペレーティングシステムを正式にサポートしていませんが、次の機能が動作することがわかっています。

* OpenShift Container Platform（AMD64およびARM64）でサポートされるRed Hat Enterprise Linux CoreOS（RHCOS）のバージョン
* RHEL 8+（AMD64およびARM64）
+

NOTE: NVMe/TCPにはRHEL 9以降が必要です。

* Ubuntu 22.04以降（AMD64およびARM64）
* Windows Server 2022


デフォルトでは、Tridentはコンテナ内で実行されるため、どのLinuxワーカーでも実行されます。ただし、使用しているバックエンドに応じて、Tridentが提供するボリュームを、標準のNFSクライアントまたはiSCSIイニシエータを使用してマウントできる必要があります。

tridentctl ユーティリティーは ' これらの Linux ディストリビューションでも動作します



== ホストの設定

Kubernetesクラスタ内のすべてのワーカーノードが、ポッド用にプロビジョニングしたボリュームをマウントできる必要があります。ワーカーノードを準備するには、ドライバの選択に基づいてNFS、iSCSI、またはNVMeのツールをインストールする必要があります。

link:../trident-use/worker-node-prep.html["ワーカーノードを準備します"]



== ストレージシステムの構成：

バックエンド構成でTridentを使用するには、ストレージシステムの変更が必要になる場合があります。

link:../trident-use/backends.html["バックエンドを設定"]



== Tridentポート

Tridentでは、通信のために特定のポートにアクセスする必要があります。

link:../trident-reference/ports.html["Tridentポート"]



== コンテナイメージと対応する Kubernetes バージョン

エアギャップを使用したインストールでは、Tridentのインストールに必要なコンテナイメージの参照先を以下に示します。コマンドを使用し `tridentctl images`て、必要なコンテナイメージのリストを確認します。



=== Trident 25.10 に必要なコンテナ イメージ

[cols="2"]
|===
| Kubernetesのバージョン | コンテナイメージ 


| v1.27.0、v1.28.0、v1.29.0、v1.30.0、v1.31.0、v1.32.0、v1.33.0、v1.34.0  a| 
* docker.io/netapp/トライデント:25.10.0
* docker.io/netapp/trident-autosupport:25.10
* registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
* registry.k8s.io/sig-storage/csi-attacher:v4.10.0
* registry.k8s.io/sig-storage/csi-resizer:v1.14.0
* registry.k8s.io/sig-storage/csi-snapshotter:v8.3.0
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
* docker.io/netapp/trident-operator:25.10.0 (オプション)


|===