---
sidebar: sidebar 
permalink: trident-protect/trident-protect-manage-applications.html 
keywords: appvault, data protection, custom resource, namespace, application, cluster 
summary: アプリケーションCRおよび関連するAppVault CRを作成することにより、管理対象のアプリケーションをTrident protectに認識させることができます。 
---
= Trident保護で管理アプリケーションを定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident protectで管理するアプリケーションを定義するには、アプリケーションCRおよび関連するAppVault CRを作成します。



== AppVault CRの作成

アプリケーションでデータ保護処理を実行するときに使用するAppVault CRを作成する必要があります。また、Trident保護がインストールされているクラスタにAppVault CRを配置する必要があります。AppVault CRはお使いの環境に固有です。AppVault CRSの例については、link:trident-protect-appvault-custom-resources.html["AppVaultカスタムリソース。"]



== アプリケーションCRの作成

Trident保護を使用して管理するアプリケーションごとに、へのアプリケーションCRを作成する必要があります。管理用のアプリケーションを追加するには、アプリケーションCRを手動で作成するか、Trident保護CLIを使用してCRを作成します。

[role="tabbed-block"]
====
.CRを使用したアプリケーションの追加
--
.手順
. デスティネーションアプリケーションのCRファイルを作成します。
+
.. カスタムリソース（CR）ファイルを作成し、という名前を付けます（例： `maria-app.yaml`）。
.. 次の属性を設定します。
+
*** * metadata.name*:（_required_）アプリケーションカスタムリソースの名前。保護操作に必要な他のCRファイルがこの値を参照するため、選択した名前をメモします。
*** * spec.includedNamespaces*:(_required_)名前空間ラベルまたは名前空間名を使用して、アプリケーションリソースが存在する名前空間を指定します。アプリケーション名前空間は、このリストの一部である必要があります。
+
YAMLの例：

+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: maria
  namespace: my-app-namespace
spec:
  includedNamespaces:
    labelSelector: {}
    namespace: my-app-namespace
----






--
.CLIを使用したアプリケーションの追加
--
.手順
. アプリケーション定義を作成して適用し、括弧内の値を環境からの情報に置き換えます。次の例に示す引数を持つカンマ区切りリストを使用して、名前空間とリソースをアプリケーション定義に含めることができます。
+
[source, console]
----
tridentctl protect create application <my_new_app_cr_name> --namespaces <namespaces_to_include> --csr <cluster_scoped_resources_to_include>
----


--
====