---
sidebar: sidebar 
permalink: trident-protect/trident-protect-cli.html 
keywords: trident, protect, command line utility, cli, netapp, custom, resources 
summary: protectctl コマンドを使用して、 Trident Protect カスタム リソースを作成し、操作することができます。 
---
= Trident Protect CLIプラグインをインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protectコマンドラインプラグインを使用できます。これはTridentの拡張機能です。 `tridentctl` Trident Protect カスタム リソース (CR) を作成し、操作するためのユーティリティです。



== Trident Protect CLIプラグインをインストールする

コマンドラインユーティリティを使用する前に、クラスタへのアクセスに使用するマシンにインストールする必要があります。マシンがx64またはARM CPUを使用しているかどうかに応じて、次の手順を実行します。

[role="tabbed-block"]
====
.Linux AMD64 CPU用プラグインのダウンロード
--
.手順
. Trident Protect CLI プラグインをダウンロードします。
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-linux-amd64
----


--
.Linux ARM64 CPU用プラグインのダウンロード
--
.手順
. Trident Protect CLI プラグインをダウンロードします。
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-linux-arm64
----


--
.Mac AMD64 CPU用プラグインのダウンロード
--
.手順
. Trident Protect CLI プラグインをダウンロードします。
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-macos-amd64
----


--
.Mac ARM64 CPU用プラグインのダウンロード
--
.手順
. Trident Protect CLI プラグインをダウンロードします。
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-macos-arm64
----


--
====
. プラグインバイナリの実行権限を有効にします。
+
[source, console]
----
chmod +x tridentctl-protect
----
. プラグインバイナリをPATH変数で定義されている場所にコピーします。たとえば、 `/usr/bin`または `/usr/local/bin`（昇格されたPrivilegesが必要な場合があります）。
+
[source, console]
----
cp ./tridentctl-protect /usr/local/bin/
----
. 必要に応じて、プラグインバイナリをホームディレクトリ内の場所にコピーできます。この場合、locationがPATH変数の一部であることを確認することをお勧めします。
+
[source, console]
----
cp ./tridentctl-protect ~/bin/
----



NOTE: プラグインをPATH変数の場所にコピーすると、任意の場所からまたはを `tridentctl protect`入力してプラグインを使用でき `tridentctl-protect`ます。



== Trident CLIプラグインのヘルプを表示

組み込みプラグインヘルプ機能を使用して、プラグインの機能に関する詳細なヘルプを表示できます。

.手順
. ヘルプ機能を使用して、使用方法に関するガイダンスを表示します。
+
[source, console]
----
tridentctl-protect help
----




== コマンドの自動補完を有効にする

Trident Protect CLI プラグインをインストールした後、特定のコマンドの自動補完を有効にすることができます。

[role="tabbed-block"]
====
.Bashシェルの自動補完を有効にする
--
.手順
. 完了スクリプトを作成します。
+
[source, console]
----
tridentctl-protect completion bash > tridentctl-completion.bash
----
. ホームディレクトリにスクリプトを格納する新しいディレクトリを作成します。
+
[source, console]
----
mkdir -p ~/.bash/completions
----
. ダウンロードしたスクリプトをディレクトリに移動し `~/.bash/completions`ます。
+
[source, console]
----
mv tridentctl-completion.bash ~/.bash/completions/
----
. ホームディレクトリ内のファイルに次の行を追加し `~/.bashrc`ます。
+
[source, console]
----
source ~/.bash/completions/tridentctl-completion.bash
----


--
.Zシェルの自動補完を有効にする
--
.手順
. 完了スクリプトを作成します。
+
[source, console]
----
tridentctl-protect completion zsh > tridentctl-completion.zsh
----
. ホームディレクトリにスクリプトを格納する新しいディレクトリを作成します。
+
[source, console]
----
mkdir -p ~/.zsh/completions
----
. ダウンロードしたスクリプトをディレクトリに移動し `~/.zsh/completions`ます。
+
[source, console]
----
mv tridentctl-completion.zsh ~/.zsh/completions/
----
. ホームディレクトリ内のファイルに次の行を追加し `~/.zprofile`ます。
+
[source, console]
----
source ~/.zsh/completions/tridentctl-completion.zsh
----


--
====
.結果
次のシェルログイン時に、tridentctl-protectプラグインで自動補完コマンドを使用できます。
