---
sidebar: sidebar 
permalink: trident-protect/trident-protect-use-execution-hooks.html 
keywords: trident, protect, execution hooks 
summary: Trident Protect を使用して、アプリのカスタム実行フックを作成できます。実行フックを作成するには、所有者、管理者、またはメンバーの権限が必要です。 
---
= Trident Protect実行フックを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
実行フックは、管理対象アプリケーションのデータ保護操作と組み合わせて実行するように構成できるカスタムアクションです。たとえば、データベースアプリケーションがある場合、実行フックを使用して、スナップショットの前にすべてのデータベーストランザクションを一時停止し、スナップショットの完了後にトランザクションを再開できます。これにより、アプリケーションと整合性のある Snapshot を作成できます。



== 実行フックのタイプ

Trident Protect は、実行できるタイミングに基づいて、次のタイプの実行フックをサポートしています。

* Snapshot前
* Snapshot後
* バックアップ前
* バックアップ後
* リストア後のPOSTコマンドです
* フェイルオーバー後




=== 実行順序

データ保護操作を実行すると、実行フックイベントが次の順序で実行されます。

. 適用可能なカスタムプリオペレーション実行フックは、適切なコンテナで実行されます。カスタムのプリオペレーションフックは必要なだけ作成して実行できますが、操作前のこれらのフックの実行順序は保証も構成もされていません。
. 該当する場合、ファイルシステムのフリーズが発生します。link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Trident Protect によるファイルシステムのフリーズ設定の詳細"]。
. データ保護処理が実行されます。
. フリーズされたファイルシステムは、該当する場合はフリーズ解除されます。
. 適用可能なカスタムポストオペレーション実行フックは、適切なコンテナで実行されます。必要な数のカスタムポストオペレーションフックを作成して実行できますが、操作後のこれらのフックの実行順序は保証されず、設定もできません。


同じ種類の実行フック（スナップショット前など）を複数作成する場合、これらのフックの実行順序は保証されません。ただし、異なるタイプのフックの実行順序は保証されています。たとえば'以下は'すべての異なるタイプのフックを持つ構成の実行順序です

. スナップショット前フックが実行されます
. スナップショット後フックが実行されます
. 予備フックが実行されます
. バックアップ後のフックが実行されます



NOTE: 上記の順序の例は、既存のSnapshotを使用しないバックアップを実行する場合にのみ該当します。


NOTE: 本番環境で実行スクリプトを有効にする前に、必ず実行フックスクリプトをテストしてください。'kubectl exec' コマンドを使用すると、スクリプトを簡単にテストできます。本番環境で実行フックを有効にしたら、作成されたSnapshotとバックアップをテストして整合性があることを確認します。これを行うには、アプリケーションを一時的なネームスペースにクローニングし、スナップショットまたはバックアップをリストアしてから、アプリケーションをテストします。


NOTE: スナップショット前の実行フックでKubernetesリソースが追加、変更、または削除された場合、それらの変更はスナップショットまたはバックアップ、および後続のリストア処理に含まれます。



== カスタム実行フックに関する重要な注意事項

アプリケーションの実行フックを計画するときは、次の点を考慮してください。

* 実行フックは、スクリプトを使用してアクションを実行する必要があります。多くの実行フックは、同じスクリプトを参照できます。
* Trident Protect では、実行フックが使用するスクリプトを実行可能なシェル スクリプトの形式で記述する必要があります。
* スクリプトのサイズは96KBに制限されています。
* Trident Protect は、実行フックの設定と一致する基準を使用して、スナップショット、バックアップ、または復元操作に適用可能なフックを決定します。



NOTE: 実行フックは、実行中のアプリケーションの機能を低下させたり、完全に無効にしたりすることが多いため、カスタム実行フックの実行時間を最小限に抑えるようにしてください。実行フックが関連付けられている状態でバックアップまたはスナップショット操作を開始した後'キャンセルした場合でも'バックアップまたはスナップショット操作がすでに開始されていればフックは実行できますつまり、バックアップ後の実行フックで使用されるロジックは、バックアップが完了したとは見なされません。



== 実行フックフィルタ

アプリケーションの実行フックを追加または編集するときに、実行フックにフィルタを追加して、フックが一致するコンテナを管理できます。フィルタは、すべてのコンテナで同じコンテナイメージを使用し、各イメージを別の目的（Elasticsearchなど）に使用するアプリケーションに便利です。フィルタを使用すると、一部の同一コンテナで実行フックが実行されるシナリオを作成できます。1つの実行フックに対して複数のフィルタを作成すると、それらは論理AND演算子と結合されます。実行フックごとに最大10個のアクティブフィルタを使用できます。

実行フックに追加する各フィルターは、正規表現を使用してクラスター内のコンテナを照合します。フックがコンテナに一致すると、フックはそのコンテナ上で関連付けられたスクリプトを実行します。フィルターの正規表現では正規表現 2 (RE2) 構文が使用されますが、一致リストからコンテナーを除外するフィルターの作成はサポートされていません。Trident Protectが実行フックフィルタでサポートする正規表現の構文については、以下を参照してください。 https://github.com/google/re2/wiki/Syntax["正規表現2（RE2）構文のサポート"^] 。


NOTE: リストアまたはクローン処理のあとに実行される実行フックにネームスペースフィルタを追加し、リストアまたはクローンのソースとデスティネーションが異なるネームスペースにある場合、ネームスペースフィルタはデスティネーションネームスペースにのみ適用されます。



== 実行フックの例

にアクセスして https://github.com/NetApp/Verda["NetApp Verda GitHubプロジェクト"] 、Apache CassandraやElasticsearchなどの一般的なアプリケーションの実際の実行フックをダウンロードします。また、独自のカスタム実行フックを構築するための例やアイデアを得ることもできます。



== 実行フックの作成

Trident Protect を使用して、アプリのカスタム実行フックを作成できます。実行フックを作成するには、所有者、管理者、またはメンバーの権限が必要です。

[role="tabbed-block"]
====
.CRの使用
--
.手順
. カスタムリソース（CR）ファイルを作成し、という名前を付け `trident-protect-hook.yaml`ます。
. Trident Protect 環境とクラスタ構成に合わせて次の属性を構成します。
+
** * metadata.name*:（_required_）このカスタムリソースの名前。環境に適した一意の適切な名前を選択します。
** *spec.applicationRef *:(_required_)実行フックを実行するアプリケーションのKubernetes名。
** *spec.stage *:(_required_)実行フックが実行されるアクションのステージを示す文字列。有効な値：
+
*** 前
*** 投稿


** *spec.action *:(_required_)指定された実行フックフィルタが一致すると仮定して、実行フックが実行するアクションを示す文字列。有効な値：
+
*** スナップショット
*** バックアップ
*** リストア
*** フェイルオーバー


** *spec.enabled *:(_Optional_)この実行フックが有効か無効かを示します。指定しない場合、デフォルト値はtrueです。
** *spec.hookSource*:(_required_) base64でエンコードされたフックスクリプトを含む文字列。
** *spec.timeout *:(_Optional _)実行フックの実行を許可する時間を分単位で定義する数値。最小値は1分で、指定しない場合のデフォルト値は25分です。
** * spec.arguments *:(_Optional _)実行フックに指定できる引数のYAMLリスト。
** *spec.matchingCriteria *:(_Optional_)実行フックフィルタを構成する各ペアの基準キー値ペアのオプションリスト。実行フックごとに最大10個のフィルタを追加できます。
** *spec.matchingCriteria.type *:(_Optional_)実行フックフィルタタイプを識別する文字列。有効な値：
+
*** コンテナイメージ
*** コンテナ名
*** ポッド名
*** PodLabel
*** ネームスペース名


** *spec.matchingCriteria.value *:(_Optional_)実行フックフィルタ値を識別する文字列または正規表現。
+
YAMLの例：

+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: ExecHook
metadata:
  name: example-hook-cr
  namespace: my-app-namespace
  annotations:
    astra.netapp.io/astra-control-hook-source-id: /account/test/hookSource/id
spec:
  applicationRef: my-app-name
  stage: Pre
  action: Snapshot
  enabled: true
  hookSource: IyEvYmluL2Jhc2gKZWNobyAiZXhhbXBsZSBzY3JpcHQiCg==
  timeout: 10
  arguments:
    - FirstExampleArg
    - SecondExampleArg
  matchingCriteria:
    - type: containerName
      value: mysql
    - type: containerImage
      value: bitnami/mysql
    - type: podName
      value: mysql
    - type: namespaceName
      value: mysql-a
    - type: podLabel
      value: app.kubernetes.io/component=primary
    - type: podLabel
      value: helm.sh/chart=mysql-10.1.0
    - type: podLabel
      value: deployment-type=production
----


. CRファイルに正しい値を入力したら、CRを適用します。
+
[source, console]
----
kubectl apply -f trident-protect-hook.yaml
----


--
.CLI を使用します
--
.手順
. 実行フックを作成し、括弧内の値を環境からの情報に置き換えます。例：
+
[source, console]
----
tridentctl-protect create exechook <my_exec_hook_name> --action <action_type> --app <app_to_use_hook> --stage <pre_or_post_stage> --source-file <script-file> -n <application_namespace>
----


--
====


== 実行フックを手動で実行する

テスト目的で、または失敗後にフックを手動で再実行する必要がある場合は、実行フックを手動で実行できます。実行フックを手動で実行するには、Owner、Admin、またはMemberの権限が必要です。

実行フックを手動で実行するには、次の2つの基本ステップがあります。

. リソースのバックアップを作成します。リソースを収集してバックアップを作成し、フックの実行場所を決定します。
. バックアップに対して実行フックを実行する


.手順1：リソースのバックアップを作成する
[%collapsible]
====
[role="tabbed-block"]
=====
.CRの使用
--
.手順
. カスタムリソース（CR）ファイルを作成し、という名前を付け `trident-protect-resource-backup.yaml`ます。
. Trident Protect 環境とクラスタ構成に合わせて次の属性を構成します。
+
** * metadata.name*:（_required_）このカスタムリソースの名前。環境に適した一意の適切な名前を選択します。
** * spec.applicationRef *：（_required_）リソースのバックアップを作成するアプリケーションのKubernetes名。
** * spec.appVaultRef *：（_required_）バックアップコンテンツが格納されているAppVaultの名前。
** *spec.appArchivePath*:バックアップコンテンツが格納されているAppVault内のパス。このパスを検索するには、次のコマンドを使用します。
+
[source, console]
----
kubectl get backups <BACKUP_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
----
+
YAMLの例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: ResourceBackup
metadata:
  name: example-resource-backup
spec:
  applicationRef: my-app-name
  appVaultRef: my-appvault-name
  appArchivePath: example-resource-backup
----


. CRファイルに正しい値を入力したら、CRを適用します。
+
[source, console]
----
kubectl apply -f trident-protect-resource-backup.yaml
----


--
.CLI を使用します
--
.手順
. バックアップを作成します。角かっこ内の値は、使用している環境の情報に置き換えます。例：
+
[source, console]
----
tridentctl protect create resourcebackup <my_backup_name> --app <my_app_name> --appvault <my_appvault_name> -n <my_app_namespace> --app-archive-path <app_archive_path>
----
. バックアップのステータスを表示します。この例のコマンドは、処理が完了するまで繰り返し使用できます。
+
[source, console]
----
tridentctl protect get resourcebackup -n <my_app_namespace> <my_backup_name>
----
. バックアップが成功したことを確認します。
+
[source, console]
----
kubectl describe resourcebackup <my_backup_name>
----


--
=====
====
.ステップ2:実行フックを実行する
[%collapsible]
====
[role="tabbed-block"]
=====
.CRの使用
--
.手順
. カスタムリソース（CR）ファイルを作成し、という名前を付け `trident-protect-hook-run.yaml`ます。
. Trident Protect 環境とクラスタ構成に合わせて次の属性を構成します。
+
** * metadata.name*:（_required_）このカスタムリソースの名前。環境に適した一意の適切な名前を選択します。
** *spec.applicationRef *:(_required_)この値が、手順1で作成したResourceBackup CRのアプリケーション名と一致していることを確認します。
** *spec.appVaultRef *:(_required_)この値が、手順1で作成したResourceBackup CRのappVaultRefと一致していることを確認します。
** *spec.appArchivePath *：この値が、手順1で作成したResourceBackup CRのappArchivePathと一致していることを確認します。
+
[source, console]
----
kubectl get backups <BACKUP_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
----
** *spec.action *:(_required_)指定された実行フックフィルタが一致すると仮定して、実行フックが実行するアクションを示す文字列。有効な値：
+
*** スナップショット
*** バックアップ
*** リストア
*** フェイルオーバー


** *spec.stage *:(_required_)実行フックが実行されるアクションのステージを示す文字列。このフックランは、他のステージではフックを実行しません。有効な値：
+
*** 前
*** 投稿
+
YAMLの例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: ExecHooksRun
metadata:
  name: example-hook-run
spec:
  applicationRef: my-app-name
  appVaultRef: my-appvault-name
  appArchivePath: example-resource-backup
  stage: Post
  action: Failover
----




. CRファイルに正しい値を入力したら、CRを適用します。
+
[source, console]
----
kubectl apply -f trident-protect-hook-run.yaml
----


--
.CLI を使用します
--
.手順
. 手動実行フック実行要求を作成します。
+
[source, console]
----
tridentctl protect create exechooksrun <my_exec_hook_run_name> -n <my_app_namespace> --action snapshot --stage <pre_or_post> --app <my_app_name> --appvault <my_appvault_name> --path <my_backup_name>
----
. 実行フック実行のステータスを確認します。このコマンドは、処理が完了するまで繰り返し実行できます。
+
[source, console]
----
tridentctl protect get exechooksrun -n <my_app_namespace> <my_exec_hook_run_name>
----
. exechooksrunオブジェクトについて説明し、最終的な詳細とステータスを確認します。
+
[source, console]
----
kubectl -n <my_app_namespace> describe exechooksrun <my_exec_hook_run_name>
----


--
=====
====