---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: 環境が要件を満たしている場合は、次の手順に従ってTrident Protectをインストールできます。 
---
= Trident保護のインストールと設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ご使用の環境がTrident保護の要件を満たしている場合は、次の手順に従ってクラスタにTrident保護をインストールします。NetAppからTrident protectを取得するか、独自のプライベートレジストリからインストールできます。プライベートレジストリからインストールすると、クラスタがインターネットにアクセスできない場合に役立ちます。



== Tridentプロテクトのインストール

[role="tabbed-block"]
====
.Trident protect from NetAppのインストール
--
.手順
. Trident Helmリポジトリを追加します。
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Helmを使用してTrident protectをインストールします。をクラスタ名に置き換えます `<name-of-cluster>`。クラスタに割り当てられ、クラスタのバックアップとスナップショットの識別に使用されます。
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2510.0 --create-namespace --namespace trident-protect
----
. オプションで、デバッグ ログを有効にするには (トラブルシューティングに推奨)、次のコマンドを使用します。
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect
----
+
デバッグ ログにより、 NetAppサポートは、ログ レベルの変更や問題の再現を必要とせずに、問題のトラブルシューティングを行うことができます。



--
.Trident protectをプライベートレジストリからインストールする
--
Kubernetesクラスタがインターネットにアクセスできない場合は、プライベートイメージレジストリからTrident protectをインストールできます。次の例では、括弧内の値を環境の情報に置き換えます。

.手順
. 次のイメージをローカルマシンにプルし、タグを更新して、プライベートレジストリにプッシュします。
+
[source, console]
----
docker.io/netapp/controller:25.10.0
docker.io/netapp/restic:25.10.0
docker.io/netapp/kopia:25.10.0
docker.io/netapp/kopiablockrestore:25.10.0
docker.io/netapp/trident-autosupport:25.10.0
docker.io/netapp/exechook:25.10.0
docker.io/netapp/resourcebackup:25.10.0
docker.io/netapp/resourcerestore:25.10.0
docker.io/netapp/resourcedelete:25.10.0
docker.io/netapp/trident-protect-utils:v1.0.0
----
+
例：

+
[source, console]
----
docker pull docker.io/netapp/controller:25.10.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.10.0 <private-registry-url>/controller:25.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.10.0
----
+

NOTE: Helmチャートを取得するには、まずインターネットにアクセスできるマシンにHelmチャートをダウンロードします。 `helm pull trident-protect --version 100.2510.0 --repo https://netapp.github.io/trident-protect-helm-chart`をコピーし、その結果を `trident-protect-100.2510.0.tgz` ファイルをオフライン環境にアップロードし、 `helm install trident-protect ./trident-protect-100.2510.0.tgz` 最後のステップのリポジトリ参照の代わりに使用します。

. Trident protect systemネームスペースを作成します。
+
[source, console]
----
kubectl create ns trident-protect
----
. レジストリにログインします。
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. プライベートレジストリ認証に使用するプルシークレットを作成します。
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Trident Helmリポジトリを追加します。
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. という名前のファイルを作成します `protectValues.yaml`。次のTrident保護設定が含まれていることを確認します。
+
[source, yaml]
----
---
imageRegistry: <private-registry-url>
imagePullSecrets:
  - name: regcred
----
+

NOTE: その `imageRegistry`そして `imagePullSecrets`値は、以下のすべてのコンポーネント画像に適用されます。 `resourcebackup`そして `resourcerestore`。レジストリ内の特定のリポジトリパスにイメージをプッシュする場合（例： `example.com:443/my-repo`) の場合は、レジストリ フィールドに完全なパスを含めます。これにより、すべての画像が `<private-registry-url>/<image-name>:<tag>`。

. Helmを使用してTrident protectをインストールします。をクラスタ名に置き換えます `<name_of_cluster>`。クラスタに割り当てられ、クラスタのバックアップとスナップショットの識別に使用されます。
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
. オプションで、デバッグ ログを有効にするには (トラブルシューティングに推奨)、次のコマンドを使用します。
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
デバッグ ログにより、 NetAppサポートは、ログ レベルの変更や問題の再現を必要とせずに、問題のトラブルシューティングを行うことができます。



--
====

NOTE: AutoSupport設定や名前空間フィルタリングなどのHelmチャートの追加設定オプションについては、以下を参照してください。 link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Trident保護インストールのカスタマイズ"]。
