---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: TridentのREST APIを操作する場合は、RESTエンドポイントを直接使用できます。 
---
= Trident REST API
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
link:tridentctl.html["tridentctl コマンドとオプション"]Trident REST APIを操作する最も簡単な方法ですが、必要に応じてRESTエンドポイントを直接使用することもできます。



== REST APIを使用する状況

REST APIは、Kubernetes以外の環境でTridentをスタンドアロンバイナリとして使用する高度なインストールに役立ちます。

セキュリティを強化するため、ポッド内で実行する場合、Tridentは `REST API`デフォルトでlocalhostに制限されています。この動作を変更するには、ポッド構成でTridentの引数を設定する必要があり `-address`ます。



== REST APIを使用する

これらのAPIの呼び出し方法の例については、debug)(`-d`フラグを渡します。詳細については、を参照してください link:../trident-managing-k8s/tridentctl.html["tridentctlを使用したTridentの管理"]。

API は次のように機能します。



=== 取得

`GET <trident-address>/trident/v1/<object-type>`:: そのタイプのすべてのオブジェクトを一覧表示します。
`GET <trident-address>/trident/v1/<object-type>/<object-name>`:: 指定したオブジェクトの詳細を取得します。




=== 投稿（ Post ）

`POST <trident-address>/trident/v1/<object-type>`:: 指定したタイプのオブジェクトを作成します。
+
--
* オブジェクトを作成するには JSON 構成が必要です。各オブジェクトタイプの仕様については、を参照してくださいlink:../trident-managing-k8s/tridentctl.html["tridentctlを使用したTridentの管理"]。
* オブジェクトがすでに存在する場合、動作は一定ではありません。バックエンドが既存のオブジェクトを更新しますが、それ以外のすべてのオブジェクトタイプで処理が失敗します。


--




=== 削除

`DELETE <trident-address>/trident/v1/<object-type>/<object-name>`:: 指定したリソースを削除します。
+
--

NOTE: バックエンドまたはストレージクラスに関連付けられているボリュームは削除されず、削除されません。詳細については、を参照してください link:../trident-managing-k8s/tridentctl.html["tridentctlを使用したTridentの管理"]。

--

